/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Added since version: 6.0.0.0
 */
@JsonPropertyOrder({
  OrderAddress.JSON_PROPERTY_ID,
  OrderAddress.JSON_PROPERTY_VERSION_ID,
  OrderAddress.JSON_PROPERTY_COUNTRY_ID,
  OrderAddress.JSON_PROPERTY_COUNTRY_STATE_ID,
  OrderAddress.JSON_PROPERTY_FIRST_NAME,
  OrderAddress.JSON_PROPERTY_LAST_NAME,
  OrderAddress.JSON_PROPERTY_STREET,
  OrderAddress.JSON_PROPERTY_ZIPCODE,
  OrderAddress.JSON_PROPERTY_CITY,
  OrderAddress.JSON_PROPERTY_COMPANY,
  OrderAddress.JSON_PROPERTY_DEPARTMENT,
  OrderAddress.JSON_PROPERTY_TITLE,
  OrderAddress.JSON_PROPERTY_VAT_ID,
  OrderAddress.JSON_PROPERTY_PHONE_NUMBER,
  OrderAddress.JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE1,
  OrderAddress.JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE2,
  OrderAddress.JSON_PROPERTY_CUSTOM_FIELDS,
  OrderAddress.JSON_PROPERTY_CREATED_AT,
  OrderAddress.JSON_PROPERTY_UPDATED_AT,
  OrderAddress.JSON_PROPERTY_COUNTRY,
  OrderAddress.JSON_PROPERTY_COUNTRY_STATE,
  OrderAddress.JSON_PROPERTY_SALUTATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class OrderAddress {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_VERSION_ID = "versionId";
  private String versionId;

  public static final String JSON_PROPERTY_COUNTRY_ID = "countryId";
  private String countryId;

  public static final String JSON_PROPERTY_COUNTRY_STATE_ID = "countryStateId";
  private String countryStateId;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_STREET = "street";
  private String street;

  public static final String JSON_PROPERTY_ZIPCODE = "zipcode";
  private String zipcode;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_COMPANY = "company";
  private String company;

  public static final String JSON_PROPERTY_DEPARTMENT = "department";
  private String department;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_VAT_ID = "vatId";
  private String vatId;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  private String phoneNumber;

  public static final String JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE1 = "additionalAddressLine1";
  private String additionalAddressLine1;

  public static final String JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE2 = "additionalAddressLine2";
  private String additionalAddressLine2;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
  private Object customFields;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private Country country;

  public static final String JSON_PROPERTY_COUNTRY_STATE = "countryState";
  private CountryState countryState;

  public static final String JSON_PROPERTY_SALUTATION = "salutation";
  private Salutation salutation;

  public OrderAddress() {
  }

  @JsonCreator
  public OrderAddress(
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
  ) {
    this();
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public OrderAddress id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public OrderAddress versionId(String versionId) {
    
    this.versionId = versionId;
    return this;
  }

   /**
   * Get versionId
   * @return versionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersionId() {
    return versionId;
  }


  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  public OrderAddress countryId(String countryId) {
    
    this.countryId = countryId;
    return this;
  }

   /**
   * Get countryId
   * @return countryId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNTRY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountryId() {
    return countryId;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }


  public OrderAddress countryStateId(String countryStateId) {
    
    this.countryStateId = countryStateId;
    return this;
  }

   /**
   * Get countryStateId
   * @return countryStateId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_STATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountryStateId() {
    return countryStateId;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_STATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryStateId(String countryStateId) {
    this.countryStateId = countryStateId;
  }


  public OrderAddress firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public OrderAddress lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public OrderAddress street(String street) {
    
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStreet() {
    return street;
  }


  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStreet(String street) {
    this.street = street;
  }


  public OrderAddress zipcode(String zipcode) {
    
    this.zipcode = zipcode;
    return this;
  }

   /**
   * Get zipcode
   * @return zipcode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZipcode() {
    return zipcode;
  }


  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZipcode(String zipcode) {
    this.zipcode = zipcode;
  }


  public OrderAddress city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCity(String city) {
    this.city = city;
  }


  public OrderAddress company(String company) {
    
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompany() {
    return company;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompany(String company) {
    this.company = company;
  }


  public OrderAddress department(String department) {
    
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPARTMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDepartment() {
    return department;
  }


  @JsonProperty(JSON_PROPERTY_DEPARTMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDepartment(String department) {
    this.department = department;
  }


  public OrderAddress title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public OrderAddress vatId(String vatId) {
    
    this.vatId = vatId;
    return this;
  }

   /**
   * Get vatId
   * @return vatId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVatId() {
    return vatId;
  }


  @JsonProperty(JSON_PROPERTY_VAT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatId(String vatId) {
    this.vatId = vatId;
  }


  public OrderAddress phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public OrderAddress additionalAddressLine1(String additionalAddressLine1) {
    
    this.additionalAddressLine1 = additionalAddressLine1;
    return this;
  }

   /**
   * Get additionalAddressLine1
   * @return additionalAddressLine1
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalAddressLine1() {
    return additionalAddressLine1;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalAddressLine1(String additionalAddressLine1) {
    this.additionalAddressLine1 = additionalAddressLine1;
  }


  public OrderAddress additionalAddressLine2(String additionalAddressLine2) {
    
    this.additionalAddressLine2 = additionalAddressLine2;
    return this;
  }

   /**
   * Get additionalAddressLine2
   * @return additionalAddressLine2
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalAddressLine2() {
    return additionalAddressLine2;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalAddressLine2(String additionalAddressLine2) {
    this.additionalAddressLine2 = additionalAddressLine2;
  }


  public OrderAddress customFields(Object customFields) {
    
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomFields() {
    return customFields;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  public OrderAddress country(Country country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Country getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(Country country) {
    this.country = country;
  }


  public OrderAddress countryState(CountryState countryState) {
    
    this.countryState = countryState;
    return this;
  }

   /**
   * Get countryState
   * @return countryState
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CountryState getCountryState() {
    return countryState;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryState(CountryState countryState) {
    this.countryState = countryState;
  }


  public OrderAddress salutation(Salutation salutation) {
    
    this.salutation = salutation;
    return this;
  }

   /**
   * Get salutation
   * @return salutation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SALUTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Salutation getSalutation() {
    return salutation;
  }


  @JsonProperty(JSON_PROPERTY_SALUTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalutation(Salutation salutation) {
    this.salutation = salutation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderAddress orderAddress = (OrderAddress) o;
    return Objects.equals(this.id, orderAddress.id) &&
        Objects.equals(this.versionId, orderAddress.versionId) &&
        Objects.equals(this.countryId, orderAddress.countryId) &&
        Objects.equals(this.countryStateId, orderAddress.countryStateId) &&
        Objects.equals(this.firstName, orderAddress.firstName) &&
        Objects.equals(this.lastName, orderAddress.lastName) &&
        Objects.equals(this.street, orderAddress.street) &&
        Objects.equals(this.zipcode, orderAddress.zipcode) &&
        Objects.equals(this.city, orderAddress.city) &&
        Objects.equals(this.company, orderAddress.company) &&
        Objects.equals(this.department, orderAddress.department) &&
        Objects.equals(this.title, orderAddress.title) &&
        Objects.equals(this.vatId, orderAddress.vatId) &&
        Objects.equals(this.phoneNumber, orderAddress.phoneNumber) &&
        Objects.equals(this.additionalAddressLine1, orderAddress.additionalAddressLine1) &&
        Objects.equals(this.additionalAddressLine2, orderAddress.additionalAddressLine2) &&
        Objects.equals(this.customFields, orderAddress.customFields) &&
        Objects.equals(this.createdAt, orderAddress.createdAt) &&
        Objects.equals(this.updatedAt, orderAddress.updatedAt) &&
        Objects.equals(this.country, orderAddress.country) &&
        Objects.equals(this.countryState, orderAddress.countryState) &&
        Objects.equals(this.salutation, orderAddress.salutation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, versionId, countryId, countryStateId, firstName, lastName, street, zipcode, city, company, department, title, vatId, phoneNumber, additionalAddressLine1, additionalAddressLine2, customFields, createdAt, updatedAt, country, countryState, salutation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderAddress {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
    sb.append("    countryStateId: ").append(toIndentedString(countryStateId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    zipcode: ").append(toIndentedString(zipcode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    vatId: ").append(toIndentedString(vatId)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    additionalAddressLine1: ").append(toIndentedString(additionalAddressLine1)).append("\n");
    sb.append("    additionalAddressLine2: ").append(toIndentedString(additionalAddressLine2)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryState: ").append(toIndentedString(countryState)).append("\n");
    sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

