/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import de.codebarista.shopware.modelextension.WithAdditionalProperties;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Added since version: 6.0.0.0
 */
@JsonPropertyOrder({
        Product.JSON_PROPERTY_ID,
        Product.JSON_PROPERTY_VERSION_ID,
        Product.JSON_PROPERTY_PARENT_ID,
        Product.JSON_PROPERTY_PARENT_VERSION_ID,
        Product.JSON_PROPERTY_MANUFACTURER_ID,
        Product.JSON_PROPERTY_PRODUCT_MANUFACTURER_VERSION_ID,
        Product.JSON_PROPERTY_UNIT_ID,
        Product.JSON_PROPERTY_TAX_ID,
        Product.JSON_PROPERTY_COVER_ID,
        Product.JSON_PROPERTY_PRODUCT_MEDIA_VERSION_ID,
        Product.JSON_PROPERTY_DELIVERY_TIME_ID,
        Product.JSON_PROPERTY_CANONICAL_PRODUCT_ID,
        Product.JSON_PROPERTY_CMS_PAGE_ID,
        Product.JSON_PROPERTY_CMS_PAGE_VERSION_ID,
        Product.JSON_PROPERTY_PRODUCT_NUMBER,
        Product.JSON_PROPERTY_RESTOCK_TIME,
        Product.JSON_PROPERTY_ACTIVE,
        Product.JSON_PROPERTY_AVAILABLE,
        Product.JSON_PROPERTY_IS_CLOSEOUT,
        Product.JSON_PROPERTY_DISPLAY_GROUP,
        Product.JSON_PROPERTY_MANUFACTURER_NUMBER,
        Product.JSON_PROPERTY_EAN,
        Product.JSON_PROPERTY_PURCHASE_STEPS,
        Product.JSON_PROPERTY_MAX_PURCHASE,
        Product.JSON_PROPERTY_MIN_PURCHASE,
        Product.JSON_PROPERTY_PURCHASE_UNIT,
        Product.JSON_PROPERTY_REFERENCE_UNIT,
        Product.JSON_PROPERTY_SHIPPING_FREE,
        Product.JSON_PROPERTY_MARK_AS_TOPSELLER,
        Product.JSON_PROPERTY_WEIGHT,
        Product.JSON_PROPERTY_WIDTH,
        Product.JSON_PROPERTY_HEIGHT,
        Product.JSON_PROPERTY_LENGTH,
        Product.JSON_PROPERTY_RELEASE_DATE,
        Product.JSON_PROPERTY_RATING_AVERAGE,
        Product.JSON_PROPERTY_CATEGORY_TREE,
        Product.JSON_PROPERTY_PROPERTY_IDS,
        Product.JSON_PROPERTY_OPTION_IDS,
        Product.JSON_PROPERTY_STREAM_IDS,
        Product.JSON_PROPERTY_TAG_IDS,
        Product.JSON_PROPERTY_CATEGORY_IDS,
        Product.JSON_PROPERTY_CHILD_COUNT,
        Product.JSON_PROPERTY_SALES,
        Product.JSON_PROPERTY_STATES,
        Product.JSON_PROPERTY_META_DESCRIPTION,
        Product.JSON_PROPERTY_NAME,
        Product.JSON_PROPERTY_KEYWORDS,
        Product.JSON_PROPERTY_DESCRIPTION,
        Product.JSON_PROPERTY_META_TITLE,
        Product.JSON_PROPERTY_PACK_UNIT,
        Product.JSON_PROPERTY_PACK_UNIT_PLURAL,
        Product.JSON_PROPERTY_CUSTOM_FIELDS,
        Product.JSON_PROPERTY_AVAILABLE_STOCK,
        Product.JSON_PROPERTY_STOCK,
        Product.JSON_PROPERTY_CALCULATED_PRICE,
        Product.JSON_PROPERTY_CALCULATED_PRICES,
        Product.JSON_PROPERTY_CALCULATED_MAX_PURCHASE,
        Product.JSON_PROPERTY_CALCULATED_CHEAPEST_PRICE,
        Product.JSON_PROPERTY_IS_NEW,
        Product.JSON_PROPERTY_SORTED_PROPERTIES,
        Product.JSON_PROPERTY_CREATED_AT,
        Product.JSON_PROPERTY_UPDATED_AT,
        Product.JSON_PROPERTY_TRANSLATED,
        Product.JSON_PROPERTY_DOWNLOADS,
        Product.JSON_PROPERTY_PARENT,
        Product.JSON_PROPERTY_CHILDREN,
        Product.JSON_PROPERTY_DELIVERY_TIME,
        Product.JSON_PROPERTY_TAX,
        Product.JSON_PROPERTY_MANUFACTURER,
        Product.JSON_PROPERTY_UNIT,
        Product.JSON_PROPERTY_COVER,
        Product.JSON_PROPERTY_CMS_PAGE,
        Product.JSON_PROPERTY_CANONICAL_PRODUCT,
        Product.JSON_PROPERTY_MEDIA,
        Product.JSON_PROPERTY_CROSS_SELLINGS,
        Product.JSON_PROPERTY_CONFIGURATOR_SETTINGS,
        Product.JSON_PROPERTY_PRODUCT_REVIEWS,
        Product.JSON_PROPERTY_MAIN_CATEGORIES,
        Product.JSON_PROPERTY_SEO_URLS,
        Product.JSON_PROPERTY_OPTIONS,
        Product.JSON_PROPERTY_PROPERTIES,
        Product.JSON_PROPERTY_CATEGORIES,
        Product.JSON_PROPERTY_STREAMS,
        Product.JSON_PROPERTY_CATEGORIES_RO,
        Product.JSON_PROPERTY_TAGS,
        Product.JSON_PROPERTY_SEO_CATEGORY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class Product extends WithAdditionalProperties {
    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_VERSION_ID = "versionId";
    private String versionId;

    public static final String JSON_PROPERTY_PARENT_ID = "parentId";
    private String parentId;

    public static final String JSON_PROPERTY_PARENT_VERSION_ID = "parentVersionId";
    private String parentVersionId;

    public static final String JSON_PROPERTY_MANUFACTURER_ID = "manufacturerId";
    private String manufacturerId;

    public static final String JSON_PROPERTY_PRODUCT_MANUFACTURER_VERSION_ID = "productManufacturerVersionId";
    private String productManufacturerVersionId;

    public static final String JSON_PROPERTY_UNIT_ID = "unitId";
    private String unitId;

    public static final String JSON_PROPERTY_TAX_ID = "taxId";
    private String taxId;

    public static final String JSON_PROPERTY_COVER_ID = "coverId";
    private String coverId;

    public static final String JSON_PROPERTY_PRODUCT_MEDIA_VERSION_ID = "productMediaVersionId";
    private String productMediaVersionId;

    public static final String JSON_PROPERTY_DELIVERY_TIME_ID = "deliveryTimeId";
    private String deliveryTimeId;

    public static final String JSON_PROPERTY_CANONICAL_PRODUCT_ID = "canonicalProductId";
    private String canonicalProductId;

    public static final String JSON_PROPERTY_CMS_PAGE_ID = "cmsPageId";
    private String cmsPageId;

    public static final String JSON_PROPERTY_CMS_PAGE_VERSION_ID = "cmsPageVersionId";
    private String cmsPageVersionId;

    public static final String JSON_PROPERTY_PRODUCT_NUMBER = "productNumber";
    private String productNumber;

    public static final String JSON_PROPERTY_RESTOCK_TIME = "restockTime";
    private Long restockTime;

    public static final String JSON_PROPERTY_ACTIVE = "active";
    private Boolean active;

    public static final String JSON_PROPERTY_AVAILABLE = "available";
    private Boolean available;

    public static final String JSON_PROPERTY_IS_CLOSEOUT = "isCloseout";
    private Boolean isCloseout;

    public static final String JSON_PROPERTY_DISPLAY_GROUP = "displayGroup";
    private String displayGroup;

    public static final String JSON_PROPERTY_MANUFACTURER_NUMBER = "manufacturerNumber";
    private String manufacturerNumber;

    public static final String JSON_PROPERTY_EAN = "ean";
    private String ean;

    public static final String JSON_PROPERTY_PURCHASE_STEPS = "purchaseSteps";
    private Long purchaseSteps;

    public static final String JSON_PROPERTY_MAX_PURCHASE = "maxPurchase";
    private Long maxPurchase;

    public static final String JSON_PROPERTY_MIN_PURCHASE = "minPurchase";
    private Long minPurchase;

    public static final String JSON_PROPERTY_PURCHASE_UNIT = "purchaseUnit";
    private Float purchaseUnit;

    public static final String JSON_PROPERTY_REFERENCE_UNIT = "referenceUnit";
    private Float referenceUnit;

    public static final String JSON_PROPERTY_SHIPPING_FREE = "shippingFree";
    private Boolean shippingFree;

    public static final String JSON_PROPERTY_MARK_AS_TOPSELLER = "markAsTopseller";
    private Boolean markAsTopseller;

    public static final String JSON_PROPERTY_WEIGHT = "weight";
    private Float weight;

    public static final String JSON_PROPERTY_WIDTH = "width";
    private Float width;

    public static final String JSON_PROPERTY_HEIGHT = "height";
    private Float height;

    public static final String JSON_PROPERTY_LENGTH = "length";
    private Float length;

    public static final String JSON_PROPERTY_RELEASE_DATE = "releaseDate";
    private OffsetDateTime releaseDate;

    public static final String JSON_PROPERTY_RATING_AVERAGE = "ratingAverage";
    private Float ratingAverage;

    public static final String JSON_PROPERTY_CATEGORY_TREE = "categoryTree";
    private List<String> categoryTree = new ArrayList<>();

    public static final String JSON_PROPERTY_PROPERTY_IDS = "propertyIds";
    private List<String> propertyIds = new ArrayList<>();

    public static final String JSON_PROPERTY_OPTION_IDS = "optionIds";
    private List<String> optionIds = new ArrayList<>();

    public static final String JSON_PROPERTY_STREAM_IDS = "streamIds";
    private List<String> streamIds = new ArrayList<>();

    public static final String JSON_PROPERTY_TAG_IDS = "tagIds";
    private List<String> tagIds = new ArrayList<>();

    public static final String JSON_PROPERTY_CATEGORY_IDS = "categoryIds";
    private List<String> categoryIds = new ArrayList<>();

    public static final String JSON_PROPERTY_CHILD_COUNT = "childCount";
    private Long childCount;

    public static final String JSON_PROPERTY_SALES = "sales";
    private Long sales;

    public static final String JSON_PROPERTY_STATES = "states";
    private List<String> states = new ArrayList<>();

    public static final String JSON_PROPERTY_META_DESCRIPTION = "metaDescription";
    private String metaDescription;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_KEYWORDS = "keywords";
    private String keywords;

    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    private String description;

    public static final String JSON_PROPERTY_META_TITLE = "metaTitle";
    private String metaTitle;

    public static final String JSON_PROPERTY_PACK_UNIT = "packUnit";
    private String packUnit;

    public static final String JSON_PROPERTY_PACK_UNIT_PLURAL = "packUnitPlural";
    private String packUnitPlural;

    public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
    private Object customFields;

    public static final String JSON_PROPERTY_AVAILABLE_STOCK = "availableStock";
    private Long availableStock;

    public static final String JSON_PROPERTY_STOCK = "stock";
    private Long stock;

    public static final String JSON_PROPERTY_CALCULATED_PRICE = "calculatedPrice";
    private Object calculatedPrice;

    public static final String JSON_PROPERTY_CALCULATED_PRICES = "calculatedPrices";
    private List<Object> calculatedPrices = new ArrayList<>();

    public static final String JSON_PROPERTY_CALCULATED_MAX_PURCHASE = "calculatedMaxPurchase";
    private Long calculatedMaxPurchase;

    public static final String JSON_PROPERTY_CALCULATED_CHEAPEST_PRICE = "calculatedCheapestPrice";
    private Object calculatedCheapestPrice;

    public static final String JSON_PROPERTY_IS_NEW = "isNew";
    private Boolean isNew;

    public static final String JSON_PROPERTY_SORTED_PROPERTIES = "sortedProperties";
    private Object sortedProperties;

    public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
    private OffsetDateTime createdAt;

    public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
    private OffsetDateTime updatedAt;

    public static final String JSON_PROPERTY_TRANSLATED = "translated";
    private Object translated;

    public static final String JSON_PROPERTY_DOWNLOADS = "downloads";
    private List<ProductDownload> downloads = new ArrayList<>();

    public static final String JSON_PROPERTY_PARENT = "parent";
    private Product parent;

    public static final String JSON_PROPERTY_CHILDREN = "children";
    private List<Product> children = new ArrayList<>();

    public static final String JSON_PROPERTY_DELIVERY_TIME = "deliveryTime";
    private DeliveryTime deliveryTime;

    public static final String JSON_PROPERTY_TAX = "tax";
    private Tax tax;

    public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
    private ProductManufacturer manufacturer;

    public static final String JSON_PROPERTY_UNIT = "unit";
    private Unit unit;

    public static final String JSON_PROPERTY_COVER = "cover";
    private ProductMedia cover;

    public static final String JSON_PROPERTY_CMS_PAGE = "cmsPage";
    private CmsPage cmsPage;

    public static final String JSON_PROPERTY_CANONICAL_PRODUCT = "canonicalProduct";
    private Product canonicalProduct;

    public static final String JSON_PROPERTY_MEDIA = "media";
    private List<ProductMedia> media = new ArrayList<>();

    public static final String JSON_PROPERTY_CROSS_SELLINGS = "crossSellings";
    private List<ProductCrossSelling> crossSellings = new ArrayList<>();

    public static final String JSON_PROPERTY_CONFIGURATOR_SETTINGS = "configuratorSettings";
    private List<ProductConfiguratorSetting> configuratorSettings = new ArrayList<>();

    public static final String JSON_PROPERTY_PRODUCT_REVIEWS = "productReviews";
    private List<ProductReview> productReviews = new ArrayList<>();

    public static final String JSON_PROPERTY_MAIN_CATEGORIES = "mainCategories";
    private List<MainCategory> mainCategories = new ArrayList<>();

    public static final String JSON_PROPERTY_SEO_URLS = "seoUrls";
    private List<SeoUrl> seoUrls = new ArrayList<>();

    public static final String JSON_PROPERTY_OPTIONS = "options";
    private List<PropertyGroupOption> options = new ArrayList<>();

    public static final String JSON_PROPERTY_PROPERTIES = "properties";
    private List<PropertyGroupOption> properties = new ArrayList<>();

    public static final String JSON_PROPERTY_CATEGORIES = "categories";
    private List<Category> categories = new ArrayList<>();

    public static final String JSON_PROPERTY_STREAMS = "streams";
    private List<ProductStream> streams = new ArrayList<>();

    public static final String JSON_PROPERTY_CATEGORIES_RO = "categoriesRo";
    private List<Category> categoriesRo = new ArrayList<>();

    public static final String JSON_PROPERTY_TAGS = "tags";
    private List<Tag> tags = new ArrayList<>();

    public static final String JSON_PROPERTY_SEO_CATEGORY = "seoCategory";
    private Category seoCategory;

    public Product() {
    }

    @JsonCreator
    public Product(
            @JsonProperty(JSON_PROPERTY_AVAILABLE) Boolean available,
            @JsonProperty(JSON_PROPERTY_DISPLAY_GROUP) String displayGroup,
            @JsonProperty(JSON_PROPERTY_RATING_AVERAGE) Float ratingAverage,
            @JsonProperty(JSON_PROPERTY_CATEGORY_TREE) List<String> categoryTree,
            @JsonProperty(JSON_PROPERTY_PROPERTY_IDS) List<String> propertyIds,
            @JsonProperty(JSON_PROPERTY_OPTION_IDS) List<String> optionIds,
            @JsonProperty(JSON_PROPERTY_STREAM_IDS) List<String> streamIds,
            @JsonProperty(JSON_PROPERTY_TAG_IDS) List<String> tagIds,
            @JsonProperty(JSON_PROPERTY_CATEGORY_IDS) List<String> categoryIds,
            @JsonProperty(JSON_PROPERTY_CHILD_COUNT) Long childCount,
            @JsonProperty(JSON_PROPERTY_SALES) Long sales,
            @JsonProperty(JSON_PROPERTY_STATES) List<String> states,
            @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt,
            @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
    ) {
        this();
        this.available = available;
        this.displayGroup = displayGroup;
        this.ratingAverage = ratingAverage;
        this.categoryTree = categoryTree;
        this.propertyIds = propertyIds;
        this.optionIds = optionIds;
        this.streamIds = streamIds;
        this.tagIds = tagIds;
        this.categoryIds = categoryIds;
        this.childCount = childCount;
        this.sales = sales;
        this.states = states;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Product id(String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }


    public Product versionId(String versionId) {

        this.versionId = versionId;
        return this;
    }

    /**
     * Get versionId
     *
     * @return versionId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getVersionId() {
        return versionId;
    }


    @JsonProperty(JSON_PROPERTY_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }


    public Product parentId(String parentId) {

        this.parentId = parentId;
        return this;
    }

    /**
     * Get parentId
     *
     * @return parentId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PARENT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getParentId() {
        return parentId;
    }


    @JsonProperty(JSON_PROPERTY_PARENT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }


    public Product parentVersionId(String parentVersionId) {

        this.parentVersionId = parentVersionId;
        return this;
    }

    /**
     * Get parentVersionId
     *
     * @return parentVersionId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PARENT_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getParentVersionId() {
        return parentVersionId;
    }


    @JsonProperty(JSON_PROPERTY_PARENT_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setParentVersionId(String parentVersionId) {
        this.parentVersionId = parentVersionId;
    }


    public Product manufacturerId(String manufacturerId) {

        this.manufacturerId = manufacturerId;
        return this;
    }

    /**
     * Get manufacturerId
     *
     * @return manufacturerId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MANUFACTURER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getManufacturerId() {
        return manufacturerId;
    }


    @JsonProperty(JSON_PROPERTY_MANUFACTURER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setManufacturerId(String manufacturerId) {
        this.manufacturerId = manufacturerId;
    }


    public Product productManufacturerVersionId(String productManufacturerVersionId) {

        this.productManufacturerVersionId = productManufacturerVersionId;
        return this;
    }

    /**
     * Get productManufacturerVersionId
     *
     * @return productManufacturerVersionId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCT_MANUFACTURER_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getProductManufacturerVersionId() {
        return productManufacturerVersionId;
    }


    @JsonProperty(JSON_PROPERTY_PRODUCT_MANUFACTURER_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProductManufacturerVersionId(String productManufacturerVersionId) {
        this.productManufacturerVersionId = productManufacturerVersionId;
    }


    public Product unitId(String unitId) {

        this.unitId = unitId;
        return this;
    }

    /**
     * Get unitId
     *
     * @return unitId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_UNIT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUnitId() {
        return unitId;
    }


    @JsonProperty(JSON_PROPERTY_UNIT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }


    public Product taxId(String taxId) {

        this.taxId = taxId;
        return this;
    }

    /**
     * Get taxId
     *
     * @return taxId
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TAX_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getTaxId() {
        return taxId;
    }


    @JsonProperty(JSON_PROPERTY_TAX_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTaxId(String taxId) {
        this.taxId = taxId;
    }


    public Product coverId(String coverId) {

        this.coverId = coverId;
        return this;
    }

    /**
     * Get coverId
     *
     * @return coverId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_COVER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCoverId() {
        return coverId;
    }


    @JsonProperty(JSON_PROPERTY_COVER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCoverId(String coverId) {
        this.coverId = coverId;
    }


    public Product productMediaVersionId(String productMediaVersionId) {

        this.productMediaVersionId = productMediaVersionId;
        return this;
    }

    /**
     * Get productMediaVersionId
     *
     * @return productMediaVersionId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCT_MEDIA_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getProductMediaVersionId() {
        return productMediaVersionId;
    }


    @JsonProperty(JSON_PROPERTY_PRODUCT_MEDIA_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProductMediaVersionId(String productMediaVersionId) {
        this.productMediaVersionId = productMediaVersionId;
    }


    public Product deliveryTimeId(String deliveryTimeId) {

        this.deliveryTimeId = deliveryTimeId;
        return this;
    }

    /**
     * Get deliveryTimeId
     *
     * @return deliveryTimeId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DELIVERY_TIME_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeliveryTimeId() {
        return deliveryTimeId;
    }


    @JsonProperty(JSON_PROPERTY_DELIVERY_TIME_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeliveryTimeId(String deliveryTimeId) {
        this.deliveryTimeId = deliveryTimeId;
    }


    public Product canonicalProductId(String canonicalProductId) {

        this.canonicalProductId = canonicalProductId;
        return this;
    }

    /**
     * Get canonicalProductId
     *
     * @return canonicalProductId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CANONICAL_PRODUCT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCanonicalProductId() {
        return canonicalProductId;
    }


    @JsonProperty(JSON_PROPERTY_CANONICAL_PRODUCT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCanonicalProductId(String canonicalProductId) {
        this.canonicalProductId = canonicalProductId;
    }


    public Product cmsPageId(String cmsPageId) {

        this.cmsPageId = cmsPageId;
        return this;
    }

    /**
     * Get cmsPageId
     *
     * @return cmsPageId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCmsPageId() {
        return cmsPageId;
    }


    @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCmsPageId(String cmsPageId) {
        this.cmsPageId = cmsPageId;
    }


    public Product cmsPageVersionId(String cmsPageVersionId) {

        this.cmsPageVersionId = cmsPageVersionId;
        return this;
    }

    /**
     * Get cmsPageVersionId
     *
     * @return cmsPageVersionId
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CMS_PAGE_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getCmsPageVersionId() {
        return cmsPageVersionId;
    }


    @JsonProperty(JSON_PROPERTY_CMS_PAGE_VERSION_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCmsPageVersionId(String cmsPageVersionId) {
        this.cmsPageVersionId = cmsPageVersionId;
    }


    public Product productNumber(String productNumber) {

        this.productNumber = productNumber;
        return this;
    }

    /**
     * Get productNumber
     *
     * @return productNumber
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_PRODUCT_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getProductNumber() {
        return productNumber;
    }


    @JsonProperty(JSON_PROPERTY_PRODUCT_NUMBER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setProductNumber(String productNumber) {
        this.productNumber = productNumber;
    }


    public Product restockTime(Long restockTime) {

        this.restockTime = restockTime;
        return this;
    }

    /**
     * Get restockTime
     *
     * @return restockTime
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RESTOCK_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getRestockTime() {
        return restockTime;
    }


    @JsonProperty(JSON_PROPERTY_RESTOCK_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRestockTime(Long restockTime) {
        this.restockTime = restockTime;
    }


    public Product active(Boolean active) {

        this.active = active;
        return this;
    }

    /**
     * Get active
     *
     * @return active
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ACTIVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getActive() {
        return active;
    }


    @JsonProperty(JSON_PROPERTY_ACTIVE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setActive(Boolean active) {
        this.active = active;
    }


    /**
     * Get available
     *
     * @return available
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AVAILABLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getAvailable() {
        return available;
    }


    public Product isCloseout(Boolean isCloseout) {

        this.isCloseout = isCloseout;
        return this;
    }

    /**
     * Get isCloseout
     *
     * @return isCloseout
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_CLOSEOUT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsCloseout() {
        return isCloseout;
    }


    @JsonProperty(JSON_PROPERTY_IS_CLOSEOUT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsCloseout(Boolean isCloseout) {
        this.isCloseout = isCloseout;
    }


    /**
     * Get displayGroup
     *
     * @return displayGroup
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISPLAY_GROUP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDisplayGroup() {
        return displayGroup;
    }


    public Product manufacturerNumber(String manufacturerNumber) {

        this.manufacturerNumber = manufacturerNumber;
        return this;
    }

    /**
     * Get manufacturerNumber
     *
     * @return manufacturerNumber
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MANUFACTURER_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getManufacturerNumber() {
        return manufacturerNumber;
    }


    @JsonProperty(JSON_PROPERTY_MANUFACTURER_NUMBER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setManufacturerNumber(String manufacturerNumber) {
        this.manufacturerNumber = manufacturerNumber;
    }


    public Product ean(String ean) {

        this.ean = ean;
        return this;
    }

    /**
     * Get ean
     *
     * @return ean
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEan() {
        return ean;
    }


    @JsonProperty(JSON_PROPERTY_EAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEan(String ean) {
        this.ean = ean;
    }


    public Product purchaseSteps(Long purchaseSteps) {

        this.purchaseSteps = purchaseSteps;
        return this;
    }

    /**
     * Get purchaseSteps
     *
     * @return purchaseSteps
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PURCHASE_STEPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getPurchaseSteps() {
        return purchaseSteps;
    }


    @JsonProperty(JSON_PROPERTY_PURCHASE_STEPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPurchaseSteps(Long purchaseSteps) {
        this.purchaseSteps = purchaseSteps;
    }


    public Product maxPurchase(Long maxPurchase) {

        this.maxPurchase = maxPurchase;
        return this;
    }

    /**
     * Get maxPurchase
     *
     * @return maxPurchase
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAX_PURCHASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getMaxPurchase() {
        return maxPurchase;
    }


    @JsonProperty(JSON_PROPERTY_MAX_PURCHASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMaxPurchase(Long maxPurchase) {
        this.maxPurchase = maxPurchase;
    }


    public Product minPurchase(Long minPurchase) {

        this.minPurchase = minPurchase;
        return this;
    }

    /**
     * Get minPurchase
     *
     * @return minPurchase
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MIN_PURCHASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getMinPurchase() {
        return minPurchase;
    }


    @JsonProperty(JSON_PROPERTY_MIN_PURCHASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMinPurchase(Long minPurchase) {
        this.minPurchase = minPurchase;
    }


    public Product purchaseUnit(Float purchaseUnit) {

        this.purchaseUnit = purchaseUnit;
        return this;
    }

    /**
     * Get purchaseUnit
     *
     * @return purchaseUnit
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PURCHASE_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getPurchaseUnit() {
        return purchaseUnit;
    }


    @JsonProperty(JSON_PROPERTY_PURCHASE_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPurchaseUnit(Float purchaseUnit) {
        this.purchaseUnit = purchaseUnit;
    }


    public Product referenceUnit(Float referenceUnit) {

        this.referenceUnit = referenceUnit;
        return this;
    }

    /**
     * Get referenceUnit
     *
     * @return referenceUnit
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REFERENCE_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getReferenceUnit() {
        return referenceUnit;
    }


    @JsonProperty(JSON_PROPERTY_REFERENCE_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setReferenceUnit(Float referenceUnit) {
        this.referenceUnit = referenceUnit;
    }


    public Product shippingFree(Boolean shippingFree) {

        this.shippingFree = shippingFree;
        return this;
    }

    /**
     * Get shippingFree
     *
     * @return shippingFree
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SHIPPING_FREE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getShippingFree() {
        return shippingFree;
    }


    @JsonProperty(JSON_PROPERTY_SHIPPING_FREE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setShippingFree(Boolean shippingFree) {
        this.shippingFree = shippingFree;
    }


    public Product markAsTopseller(Boolean markAsTopseller) {

        this.markAsTopseller = markAsTopseller;
        return this;
    }

    /**
     * Get markAsTopseller
     *
     * @return markAsTopseller
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MARK_AS_TOPSELLER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getMarkAsTopseller() {
        return markAsTopseller;
    }


    @JsonProperty(JSON_PROPERTY_MARK_AS_TOPSELLER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMarkAsTopseller(Boolean markAsTopseller) {
        this.markAsTopseller = markAsTopseller;
    }


    public Product weight(Float weight) {

        this.weight = weight;
        return this;
    }

    /**
     * Get weight
     *
     * @return weight
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WEIGHT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getWeight() {
        return weight;
    }


    @JsonProperty(JSON_PROPERTY_WEIGHT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWeight(Float weight) {
        this.weight = weight;
    }


    public Product width(Float width) {

        this.width = width;
        return this;
    }

    /**
     * Get width
     *
     * @return width
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WIDTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getWidth() {
        return width;
    }


    @JsonProperty(JSON_PROPERTY_WIDTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWidth(Float width) {
        this.width = width;
    }


    public Product height(Float height) {

        this.height = height;
        return this;
    }

    /**
     * Get height
     *
     * @return height
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_HEIGHT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getHeight() {
        return height;
    }


    @JsonProperty(JSON_PROPERTY_HEIGHT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHeight(Float height) {
        this.height = height;
    }


    public Product length(Float length) {

        this.length = length;
        return this;
    }

    /**
     * Get length
     *
     * @return length
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LENGTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getLength() {
        return length;
    }


    @JsonProperty(JSON_PROPERTY_LENGTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLength(Float length) {
        this.length = length;
    }


    public Product releaseDate(OffsetDateTime releaseDate) {

        this.releaseDate = releaseDate;
        return this;
    }

    /**
     * Get releaseDate
     *
     * @return releaseDate
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RELEASE_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getReleaseDate() {
        return releaseDate;
    }


    @JsonProperty(JSON_PROPERTY_RELEASE_DATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setReleaseDate(OffsetDateTime releaseDate) {
        this.releaseDate = releaseDate;
    }


    /**
     * Get ratingAverage
     *
     * @return ratingAverage
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RATING_AVERAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Float getRatingAverage() {
        return ratingAverage;
    }


    /**
     * Get categoryTree
     *
     * @return categoryTree
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CATEGORY_TREE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getCategoryTree() {
        return categoryTree;
    }


    /**
     * Get propertyIds
     *
     * @return propertyIds
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROPERTY_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getPropertyIds() {
        return propertyIds;
    }


    /**
     * Get optionIds
     *
     * @return optionIds
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_OPTION_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getOptionIds() {
        return optionIds;
    }


    /**
     * Get streamIds
     *
     * @return streamIds
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STREAM_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getStreamIds() {
        return streamIds;
    }


    /**
     * Get tagIds
     *
     * @return tagIds
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TAG_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getTagIds() {
        return tagIds;
    }


    /**
     * Get categoryIds
     *
     * @return categoryIds
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CATEGORY_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getCategoryIds() {
        return categoryIds;
    }


    /**
     * Get childCount
     *
     * @return childCount
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CHILD_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getChildCount() {
        return childCount;
    }


    /**
     * Get sales
     *
     * @return sales
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SALES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getSales() {
        return sales;
    }


    /**
     * Get states
     *
     * @return states
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STATES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getStates() {
        return states;
    }


    public Product metaDescription(String metaDescription) {

        this.metaDescription = metaDescription;
        return this;
    }

    /**
     * Get metaDescription
     *
     * @return metaDescription
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_META_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMetaDescription() {
        return metaDescription;
    }


    @JsonProperty(JSON_PROPERTY_META_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }


    public Product name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getName() {
        return name;
    }


    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setName(String name) {
        this.name = name;
    }


    public Product keywords(String keywords) {

        this.keywords = keywords;
        return this;
    }

    /**
     * Get keywords
     *
     * @return keywords
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_KEYWORDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeywords() {
        return keywords;
    }


    @JsonProperty(JSON_PROPERTY_KEYWORDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }


    public Product description(String description) {

        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDescription() {
        return description;
    }


    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDescription(String description) {
        this.description = description;
    }


    public Product metaTitle(String metaTitle) {

        this.metaTitle = metaTitle;
        return this;
    }

    /**
     * Get metaTitle
     *
     * @return metaTitle
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_META_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMetaTitle() {
        return metaTitle;
    }


    @JsonProperty(JSON_PROPERTY_META_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }


    public Product packUnit(String packUnit) {

        this.packUnit = packUnit;
        return this;
    }

    /**
     * Get packUnit
     *
     * @return packUnit
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PACK_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPackUnit() {
        return packUnit;
    }


    @JsonProperty(JSON_PROPERTY_PACK_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPackUnit(String packUnit) {
        this.packUnit = packUnit;
    }


    public Product packUnitPlural(String packUnitPlural) {

        this.packUnitPlural = packUnitPlural;
        return this;
    }

    /**
     * Get packUnitPlural
     *
     * @return packUnitPlural
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PACK_UNIT_PLURAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPackUnitPlural() {
        return packUnitPlural;
    }


    @JsonProperty(JSON_PROPERTY_PACK_UNIT_PLURAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPackUnitPlural(String packUnitPlural) {
        this.packUnitPlural = packUnitPlural;
    }


    public Product customFields(Object customFields) {

        this.customFields = customFields;
        return this;
    }

    /**
     * Get customFields
     *
     * @return customFields
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Object getCustomFields() {
        return customFields;
    }


    @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCustomFields(Object customFields) {
        this.customFields = customFields;
    }


    public Product availableStock(Long availableStock) {

        this.availableStock = availableStock;
        return this;
    }

    /**
     * Get availableStock
     *
     * @return availableStock
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AVAILABLE_STOCK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getAvailableStock() {
        return availableStock;
    }


    @JsonProperty(JSON_PROPERTY_AVAILABLE_STOCK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAvailableStock(Long availableStock) {
        this.availableStock = availableStock;
    }


    public Product stock(Long stock) {

        this.stock = stock;
        return this;
    }

    /**
     * Get stock
     *
     * @return stock
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_STOCK)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Long getStock() {
        return stock;
    }


    @JsonProperty(JSON_PROPERTY_STOCK)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStock(Long stock) {
        this.stock = stock;
    }


    public Product calculatedPrice(Object calculatedPrice) {

        this.calculatedPrice = calculatedPrice;
        return this;
    }

    /**
     * Get calculatedPrice
     *
     * @return calculatedPrice
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CALCULATED_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Object getCalculatedPrice() {
        return calculatedPrice;
    }


    @JsonProperty(JSON_PROPERTY_CALCULATED_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCalculatedPrice(Object calculatedPrice) {
        this.calculatedPrice = calculatedPrice;
    }


    public Product calculatedPrices(List<Object> calculatedPrices) {

        this.calculatedPrices = calculatedPrices;
        return this;
    }

    public Product addCalculatedPricesItem(Object calculatedPricesItem) {
        if (this.calculatedPrices == null) {
            this.calculatedPrices = new ArrayList<>();
        }
        this.calculatedPrices.add(calculatedPricesItem);
        return this;
    }

    /**
     * Get calculatedPrices
     *
     * @return calculatedPrices
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CALCULATED_PRICES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Object> getCalculatedPrices() {
        return calculatedPrices;
    }


    @JsonProperty(JSON_PROPERTY_CALCULATED_PRICES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCalculatedPrices(List<Object> calculatedPrices) {
        this.calculatedPrices = calculatedPrices;
    }


    public Product calculatedMaxPurchase(Long calculatedMaxPurchase) {

        this.calculatedMaxPurchase = calculatedMaxPurchase;
        return this;
    }

    /**
     * Runtime field, cannot be used as part of the criteria.
     *
     * @return calculatedMaxPurchase
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CALCULATED_MAX_PURCHASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Long getCalculatedMaxPurchase() {
        return calculatedMaxPurchase;
    }


    @JsonProperty(JSON_PROPERTY_CALCULATED_MAX_PURCHASE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCalculatedMaxPurchase(Long calculatedMaxPurchase) {
        this.calculatedMaxPurchase = calculatedMaxPurchase;
    }


    public Product calculatedCheapestPrice(Object calculatedCheapestPrice) {

        this.calculatedCheapestPrice = calculatedCheapestPrice;
        return this;
    }

    /**
     * Get calculatedCheapestPrice
     *
     * @return calculatedCheapestPrice
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CALCULATED_CHEAPEST_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Object getCalculatedCheapestPrice() {
        return calculatedCheapestPrice;
    }


    @JsonProperty(JSON_PROPERTY_CALCULATED_CHEAPEST_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCalculatedCheapestPrice(Object calculatedCheapestPrice) {
        this.calculatedCheapestPrice = calculatedCheapestPrice;
    }


    public Product isNew(Boolean isNew) {

        this.isNew = isNew;
        return this;
    }

    /**
     * Runtime field, cannot be used as part of the criteria.
     *
     * @return isNew
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_NEW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsNew() {
        return isNew;
    }


    @JsonProperty(JSON_PROPERTY_IS_NEW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }


    public Product sortedProperties(Object sortedProperties) {

        this.sortedProperties = sortedProperties;
        return this;
    }

    /**
     * Get sortedProperties
     *
     * @return sortedProperties
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SORTED_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Object getSortedProperties() {
        return sortedProperties;
    }


    @JsonProperty(JSON_PROPERTY_SORTED_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSortedProperties(Object sortedProperties) {
        this.sortedProperties = sortedProperties;
    }


    /**
     * Get createdAt
     *
     * @return createdAt
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_CREATED_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }


    /**
     * Get updatedAt
     *
     * @return updatedAt
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }


    public Product translated(Object translated) {

        this.translated = translated;
        return this;
    }

    /**
     * Get translated
     *
     * @return translated
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSLATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Object getTranslated() {
        return translated;
    }


    @JsonProperty(JSON_PROPERTY_TRANSLATED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTranslated(Object translated) {
        this.translated = translated;
    }


    public Product downloads(List<ProductDownload> downloads) {

        this.downloads = downloads;
        return this;
    }

    public Product addDownloadsItem(ProductDownload downloadsItem) {
        if (this.downloads == null) {
            this.downloads = new ArrayList<>();
        }
        this.downloads.add(downloadsItem);
        return this;
    }

    /**
     * Get downloads
     *
     * @return downloads
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DOWNLOADS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProductDownload> getDownloads() {
        return downloads;
    }


    @JsonProperty(JSON_PROPERTY_DOWNLOADS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDownloads(List<ProductDownload> downloads) {
        this.downloads = downloads;
    }


    public Product parent(Product parent) {

        this.parent = parent;
        return this;
    }

    /**
     * Get parent
     *
     * @return parent
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PARENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Product getParent() {
        return parent;
    }


    @JsonProperty(JSON_PROPERTY_PARENT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setParent(Product parent) {
        this.parent = parent;
    }


    public Product children(List<Product> children) {

        this.children = children;
        return this;
    }

    public Product addChildrenItem(Product childrenItem) {
        if (this.children == null) {
            this.children = new ArrayList<>();
        }
        this.children.add(childrenItem);
        return this;
    }

    /**
     * Get children
     *
     * @return children
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CHILDREN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Product> getChildren() {
        return children;
    }


    @JsonProperty(JSON_PROPERTY_CHILDREN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setChildren(List<Product> children) {
        this.children = children;
    }


    public Product deliveryTime(DeliveryTime deliveryTime) {

        this.deliveryTime = deliveryTime;
        return this;
    }

    /**
     * Get deliveryTime
     *
     * @return deliveryTime
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DELIVERY_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DeliveryTime getDeliveryTime() {
        return deliveryTime;
    }


    @JsonProperty(JSON_PROPERTY_DELIVERY_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeliveryTime(DeliveryTime deliveryTime) {
        this.deliveryTime = deliveryTime;
    }


    public Product tax(Tax tax) {

        this.tax = tax;
        return this;
    }

    /**
     * Get tax
     *
     * @return tax
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TAX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Tax getTax() {
        return tax;
    }


    @JsonProperty(JSON_PROPERTY_TAX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTax(Tax tax) {
        this.tax = tax;
    }


    public Product manufacturer(ProductManufacturer manufacturer) {

        this.manufacturer = manufacturer;
        return this;
    }

    /**
     * Get manufacturer
     *
     * @return manufacturer
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MANUFACTURER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ProductManufacturer getManufacturer() {
        return manufacturer;
    }


    @JsonProperty(JSON_PROPERTY_MANUFACTURER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setManufacturer(ProductManufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }


    public Product unit(Unit unit) {

        this.unit = unit;
        return this;
    }

    /**
     * Get unit
     *
     * @return unit
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Unit getUnit() {
        return unit;
    }


    @JsonProperty(JSON_PROPERTY_UNIT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUnit(Unit unit) {
        this.unit = unit;
    }


    public Product cover(ProductMedia cover) {

        this.cover = cover;
        return this;
    }

    /**
     * Get cover
     *
     * @return cover
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_COVER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ProductMedia getCover() {
        return cover;
    }


    @JsonProperty(JSON_PROPERTY_COVER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCover(ProductMedia cover) {
        this.cover = cover;
    }


    public Product cmsPage(CmsPage cmsPage) {

        this.cmsPage = cmsPage;
        return this;
    }

    /**
     * Get cmsPage
     *
     * @return cmsPage
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CMS_PAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public CmsPage getCmsPage() {
        return cmsPage;
    }


    @JsonProperty(JSON_PROPERTY_CMS_PAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCmsPage(CmsPage cmsPage) {
        this.cmsPage = cmsPage;
    }


    public Product canonicalProduct(Product canonicalProduct) {

        this.canonicalProduct = canonicalProduct;
        return this;
    }

    /**
     * Get canonicalProduct
     *
     * @return canonicalProduct
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CANONICAL_PRODUCT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Product getCanonicalProduct() {
        return canonicalProduct;
    }


    @JsonProperty(JSON_PROPERTY_CANONICAL_PRODUCT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCanonicalProduct(Product canonicalProduct) {
        this.canonicalProduct = canonicalProduct;
    }


    public Product media(List<ProductMedia> media) {

        this.media = media;
        return this;
    }

    public Product addMediaItem(ProductMedia mediaItem) {
        if (this.media == null) {
            this.media = new ArrayList<>();
        }
        this.media.add(mediaItem);
        return this;
    }

    /**
     * Get media
     *
     * @return media
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MEDIA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProductMedia> getMedia() {
        return media;
    }


    @JsonProperty(JSON_PROPERTY_MEDIA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMedia(List<ProductMedia> media) {
        this.media = media;
    }


    public Product crossSellings(List<ProductCrossSelling> crossSellings) {

        this.crossSellings = crossSellings;
        return this;
    }

    public Product addCrossSellingsItem(ProductCrossSelling crossSellingsItem) {
        if (this.crossSellings == null) {
            this.crossSellings = new ArrayList<>();
        }
        this.crossSellings.add(crossSellingsItem);
        return this;
    }

    /**
     * Get crossSellings
     *
     * @return crossSellings
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CROSS_SELLINGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProductCrossSelling> getCrossSellings() {
        return crossSellings;
    }


    @JsonProperty(JSON_PROPERTY_CROSS_SELLINGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCrossSellings(List<ProductCrossSelling> crossSellings) {
        this.crossSellings = crossSellings;
    }


    public Product configuratorSettings(List<ProductConfiguratorSetting> configuratorSettings) {

        this.configuratorSettings = configuratorSettings;
        return this;
    }

    public Product addConfiguratorSettingsItem(ProductConfiguratorSetting configuratorSettingsItem) {
        if (this.configuratorSettings == null) {
            this.configuratorSettings = new ArrayList<>();
        }
        this.configuratorSettings.add(configuratorSettingsItem);
        return this;
    }

    /**
     * Get configuratorSettings
     *
     * @return configuratorSettings
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CONFIGURATOR_SETTINGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProductConfiguratorSetting> getConfiguratorSettings() {
        return configuratorSettings;
    }


    @JsonProperty(JSON_PROPERTY_CONFIGURATOR_SETTINGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setConfiguratorSettings(List<ProductConfiguratorSetting> configuratorSettings) {
        this.configuratorSettings = configuratorSettings;
    }


    public Product productReviews(List<ProductReview> productReviews) {

        this.productReviews = productReviews;
        return this;
    }

    public Product addProductReviewsItem(ProductReview productReviewsItem) {
        if (this.productReviews == null) {
            this.productReviews = new ArrayList<>();
        }
        this.productReviews.add(productReviewsItem);
        return this;
    }

    /**
     * Get productReviews
     *
     * @return productReviews
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCT_REVIEWS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProductReview> getProductReviews() {
        return productReviews;
    }


    @JsonProperty(JSON_PROPERTY_PRODUCT_REVIEWS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProductReviews(List<ProductReview> productReviews) {
        this.productReviews = productReviews;
    }


    public Product mainCategories(List<MainCategory> mainCategories) {

        this.mainCategories = mainCategories;
        return this;
    }

    public Product addMainCategoriesItem(MainCategory mainCategoriesItem) {
        if (this.mainCategories == null) {
            this.mainCategories = new ArrayList<>();
        }
        this.mainCategories.add(mainCategoriesItem);
        return this;
    }

    /**
     * Get mainCategories
     *
     * @return mainCategories
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MAIN_CATEGORIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<MainCategory> getMainCategories() {
        return mainCategories;
    }


    @JsonProperty(JSON_PROPERTY_MAIN_CATEGORIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMainCategories(List<MainCategory> mainCategories) {
        this.mainCategories = mainCategories;
    }


    public Product seoUrls(List<SeoUrl> seoUrls) {

        this.seoUrls = seoUrls;
        return this;
    }

    public Product addSeoUrlsItem(SeoUrl seoUrlsItem) {
        if (this.seoUrls == null) {
            this.seoUrls = new ArrayList<>();
        }
        this.seoUrls.add(seoUrlsItem);
        return this;
    }

    /**
     * Get seoUrls
     *
     * @return seoUrls
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SEO_URLS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<SeoUrl> getSeoUrls() {
        return seoUrls;
    }


    @JsonProperty(JSON_PROPERTY_SEO_URLS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSeoUrls(List<SeoUrl> seoUrls) {
        this.seoUrls = seoUrls;
    }


    public Product options(List<PropertyGroupOption> options) {

        this.options = options;
        return this;
    }

    public Product addOptionsItem(PropertyGroupOption optionsItem) {
        if (this.options == null) {
            this.options = new ArrayList<>();
        }
        this.options.add(optionsItem);
        return this;
    }

    /**
     * Get options
     *
     * @return options
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_OPTIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<PropertyGroupOption> getOptions() {
        return options;
    }


    @JsonProperty(JSON_PROPERTY_OPTIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOptions(List<PropertyGroupOption> options) {
        this.options = options;
    }


    public Product properties(List<PropertyGroupOption> properties) {

        this.properties = properties;
        return this;
    }

    public Product addPropertiesItem(PropertyGroupOption propertiesItem) {
        if (this.properties == null) {
            this.properties = new ArrayList<>();
        }
        this.properties.add(propertiesItem);
        return this;
    }

    /**
     * Get properties
     *
     * @return properties
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<PropertyGroupOption> getProperties() {
        return properties;
    }


    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProperties(List<PropertyGroupOption> properties) {
        this.properties = properties;
    }


    public Product categories(List<Category> categories) {

        this.categories = categories;
        return this;
    }

    public Product addCategoriesItem(Category categoriesItem) {
        if (this.categories == null) {
            this.categories = new ArrayList<>();
        }
        this.categories.add(categoriesItem);
        return this;
    }

    /**
     * Get categories
     *
     * @return categories
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CATEGORIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Category> getCategories() {
        return categories;
    }


    @JsonProperty(JSON_PROPERTY_CATEGORIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCategories(List<Category> categories) {
        this.categories = categories;
    }


    public Product streams(List<ProductStream> streams) {

        this.streams = streams;
        return this;
    }

    public Product addStreamsItem(ProductStream streamsItem) {
        if (this.streams == null) {
            this.streams = new ArrayList<>();
        }
        this.streams.add(streamsItem);
        return this;
    }

    /**
     * Get streams
     *
     * @return streams
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STREAMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProductStream> getStreams() {
        return streams;
    }


    @JsonProperty(JSON_PROPERTY_STREAMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStreams(List<ProductStream> streams) {
        this.streams = streams;
    }


    public Product categoriesRo(List<Category> categoriesRo) {

        this.categoriesRo = categoriesRo;
        return this;
    }

    public Product addCategoriesRoItem(Category categoriesRoItem) {
        if (this.categoriesRo == null) {
            this.categoriesRo = new ArrayList<>();
        }
        this.categoriesRo.add(categoriesRoItem);
        return this;
    }

    /**
     * Get categoriesRo
     *
     * @return categoriesRo
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CATEGORIES_RO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Category> getCategoriesRo() {
        return categoriesRo;
    }


    @JsonProperty(JSON_PROPERTY_CATEGORIES_RO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCategoriesRo(List<Category> categoriesRo) {
        this.categoriesRo = categoriesRo;
    }


    public Product tags(List<Tag> tags) {

        this.tags = tags;
        return this;
    }

    public Product addTagsItem(Tag tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     *
     * @return tags
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TAGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Tag> getTags() {
        return tags;
    }


    @JsonProperty(JSON_PROPERTY_TAGS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTags(List<Tag> tags) {
        this.tags = tags;
    }


    public Product seoCategory(Category seoCategory) {

        this.seoCategory = seoCategory;
        return this;
    }

    /**
     * Get seoCategory
     *
     * @return seoCategory
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SEO_CATEGORY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Category getSeoCategory() {
        return seoCategory;
    }


    @JsonProperty(JSON_PROPERTY_SEO_CATEGORY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSeoCategory(Category seoCategory) {
        this.seoCategory = seoCategory;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Product product = (Product) o;
        return Objects.equals(this.id, product.id) &&
                Objects.equals(this.versionId, product.versionId) &&
                Objects.equals(this.parentId, product.parentId) &&
                Objects.equals(this.parentVersionId, product.parentVersionId) &&
                Objects.equals(this.manufacturerId, product.manufacturerId) &&
                Objects.equals(this.productManufacturerVersionId, product.productManufacturerVersionId) &&
                Objects.equals(this.unitId, product.unitId) &&
                Objects.equals(this.taxId, product.taxId) &&
                Objects.equals(this.coverId, product.coverId) &&
                Objects.equals(this.productMediaVersionId, product.productMediaVersionId) &&
                Objects.equals(this.deliveryTimeId, product.deliveryTimeId) &&
                Objects.equals(this.canonicalProductId, product.canonicalProductId) &&
                Objects.equals(this.cmsPageId, product.cmsPageId) &&
                Objects.equals(this.cmsPageVersionId, product.cmsPageVersionId) &&
                Objects.equals(this.productNumber, product.productNumber) &&
                Objects.equals(this.restockTime, product.restockTime) &&
                Objects.equals(this.active, product.active) &&
                Objects.equals(this.available, product.available) &&
                Objects.equals(this.isCloseout, product.isCloseout) &&
                Objects.equals(this.displayGroup, product.displayGroup) &&
                Objects.equals(this.manufacturerNumber, product.manufacturerNumber) &&
                Objects.equals(this.ean, product.ean) &&
                Objects.equals(this.purchaseSteps, product.purchaseSteps) &&
                Objects.equals(this.maxPurchase, product.maxPurchase) &&
                Objects.equals(this.minPurchase, product.minPurchase) &&
                Objects.equals(this.purchaseUnit, product.purchaseUnit) &&
                Objects.equals(this.referenceUnit, product.referenceUnit) &&
                Objects.equals(this.shippingFree, product.shippingFree) &&
                Objects.equals(this.markAsTopseller, product.markAsTopseller) &&
                Objects.equals(this.weight, product.weight) &&
                Objects.equals(this.width, product.width) &&
                Objects.equals(this.height, product.height) &&
                Objects.equals(this.length, product.length) &&
                Objects.equals(this.releaseDate, product.releaseDate) &&
                Objects.equals(this.ratingAverage, product.ratingAverage) &&
                Objects.equals(this.categoryTree, product.categoryTree) &&
                Objects.equals(this.propertyIds, product.propertyIds) &&
                Objects.equals(this.optionIds, product.optionIds) &&
                Objects.equals(this.streamIds, product.streamIds) &&
                Objects.equals(this.tagIds, product.tagIds) &&
                Objects.equals(this.categoryIds, product.categoryIds) &&
                Objects.equals(this.childCount, product.childCount) &&
                Objects.equals(this.sales, product.sales) &&
                Objects.equals(this.states, product.states) &&
                Objects.equals(this.metaDescription, product.metaDescription) &&
                Objects.equals(this.name, product.name) &&
                Objects.equals(this.keywords, product.keywords) &&
                Objects.equals(this.description, product.description) &&
                Objects.equals(this.metaTitle, product.metaTitle) &&
                Objects.equals(this.packUnit, product.packUnit) &&
                Objects.equals(this.packUnitPlural, product.packUnitPlural) &&
                Objects.equals(this.customFields, product.customFields) &&
                Objects.equals(this.availableStock, product.availableStock) &&
                Objects.equals(this.stock, product.stock) &&
                Objects.equals(this.calculatedPrice, product.calculatedPrice) &&
                Objects.equals(this.calculatedPrices, product.calculatedPrices) &&
                Objects.equals(this.calculatedMaxPurchase, product.calculatedMaxPurchase) &&
                Objects.equals(this.calculatedCheapestPrice, product.calculatedCheapestPrice) &&
                Objects.equals(this.isNew, product.isNew) &&
                Objects.equals(this.sortedProperties, product.sortedProperties) &&
                Objects.equals(this.createdAt, product.createdAt) &&
                Objects.equals(this.updatedAt, product.updatedAt) &&
                Objects.equals(this.translated, product.translated) &&
                Objects.equals(this.downloads, product.downloads) &&
                Objects.equals(this.parent, product.parent) &&
                Objects.equals(this.children, product.children) &&
                Objects.equals(this.deliveryTime, product.deliveryTime) &&
                Objects.equals(this.tax, product.tax) &&
                Objects.equals(this.manufacturer, product.manufacturer) &&
                Objects.equals(this.unit, product.unit) &&
                Objects.equals(this.cover, product.cover) &&
                Objects.equals(this.cmsPage, product.cmsPage) &&
                Objects.equals(this.canonicalProduct, product.canonicalProduct) &&
                Objects.equals(this.media, product.media) &&
                Objects.equals(this.crossSellings, product.crossSellings) &&
                Objects.equals(this.configuratorSettings, product.configuratorSettings) &&
                Objects.equals(this.productReviews, product.productReviews) &&
                Objects.equals(this.mainCategories, product.mainCategories) &&
                Objects.equals(this.seoUrls, product.seoUrls) &&
                Objects.equals(this.options, product.options) &&
                Objects.equals(this.properties, product.properties) &&
                Objects.equals(this.categories, product.categories) &&
                Objects.equals(this.streams, product.streams) &&
                Objects.equals(this.categoriesRo, product.categoriesRo) &&
                Objects.equals(this.tags, product.tags) &&
                Objects.equals(this.seoCategory, product.seoCategory);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, versionId, parentId, parentVersionId, manufacturerId, productManufacturerVersionId, unitId, taxId, coverId, productMediaVersionId, deliveryTimeId, canonicalProductId, cmsPageId, cmsPageVersionId, productNumber, restockTime, active, available, isCloseout, displayGroup, manufacturerNumber, ean, purchaseSteps, maxPurchase, minPurchase, purchaseUnit, referenceUnit, shippingFree, markAsTopseller, weight, width, height, length, releaseDate, ratingAverage, categoryTree, propertyIds, optionIds, streamIds, tagIds, categoryIds, childCount, sales, states, metaDescription, name, keywords, description, metaTitle, packUnit, packUnitPlural, customFields, availableStock, stock, calculatedPrice, calculatedPrices, calculatedMaxPurchase, calculatedCheapestPrice, isNew, sortedProperties, createdAt, updatedAt, translated, downloads, parent, children, deliveryTime, tax, manufacturer, unit, cover, cmsPage, canonicalProduct, media, crossSellings, configuratorSettings, productReviews, mainCategories, seoUrls, options, properties, categories, streams, categoriesRo, tags, seoCategory);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Product {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
        sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
        sb.append("    parentVersionId: ").append(toIndentedString(parentVersionId)).append("\n");
        sb.append("    manufacturerId: ").append(toIndentedString(manufacturerId)).append("\n");
        sb.append("    productManufacturerVersionId: ").append(toIndentedString(productManufacturerVersionId)).append("\n");
        sb.append("    unitId: ").append(toIndentedString(unitId)).append("\n");
        sb.append("    taxId: ").append(toIndentedString(taxId)).append("\n");
        sb.append("    coverId: ").append(toIndentedString(coverId)).append("\n");
        sb.append("    productMediaVersionId: ").append(toIndentedString(productMediaVersionId)).append("\n");
        sb.append("    deliveryTimeId: ").append(toIndentedString(deliveryTimeId)).append("\n");
        sb.append("    canonicalProductId: ").append(toIndentedString(canonicalProductId)).append("\n");
        sb.append("    cmsPageId: ").append(toIndentedString(cmsPageId)).append("\n");
        sb.append("    cmsPageVersionId: ").append(toIndentedString(cmsPageVersionId)).append("\n");
        sb.append("    productNumber: ").append(toIndentedString(productNumber)).append("\n");
        sb.append("    restockTime: ").append(toIndentedString(restockTime)).append("\n");
        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("    available: ").append(toIndentedString(available)).append("\n");
        sb.append("    isCloseout: ").append(toIndentedString(isCloseout)).append("\n");
        sb.append("    displayGroup: ").append(toIndentedString(displayGroup)).append("\n");
        sb.append("    manufacturerNumber: ").append(toIndentedString(manufacturerNumber)).append("\n");
        sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
        sb.append("    purchaseSteps: ").append(toIndentedString(purchaseSteps)).append("\n");
        sb.append("    maxPurchase: ").append(toIndentedString(maxPurchase)).append("\n");
        sb.append("    minPurchase: ").append(toIndentedString(minPurchase)).append("\n");
        sb.append("    purchaseUnit: ").append(toIndentedString(purchaseUnit)).append("\n");
        sb.append("    referenceUnit: ").append(toIndentedString(referenceUnit)).append("\n");
        sb.append("    shippingFree: ").append(toIndentedString(shippingFree)).append("\n");
        sb.append("    markAsTopseller: ").append(toIndentedString(markAsTopseller)).append("\n");
        sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
        sb.append("    width: ").append(toIndentedString(width)).append("\n");
        sb.append("    height: ").append(toIndentedString(height)).append("\n");
        sb.append("    length: ").append(toIndentedString(length)).append("\n");
        sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
        sb.append("    ratingAverage: ").append(toIndentedString(ratingAverage)).append("\n");
        sb.append("    categoryTree: ").append(toIndentedString(categoryTree)).append("\n");
        sb.append("    propertyIds: ").append(toIndentedString(propertyIds)).append("\n");
        sb.append("    optionIds: ").append(toIndentedString(optionIds)).append("\n");
        sb.append("    streamIds: ").append(toIndentedString(streamIds)).append("\n");
        sb.append("    tagIds: ").append(toIndentedString(tagIds)).append("\n");
        sb.append("    categoryIds: ").append(toIndentedString(categoryIds)).append("\n");
        sb.append("    childCount: ").append(toIndentedString(childCount)).append("\n");
        sb.append("    sales: ").append(toIndentedString(sales)).append("\n");
        sb.append("    states: ").append(toIndentedString(states)).append("\n");
        sb.append("    metaDescription: ").append(toIndentedString(metaDescription)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    metaTitle: ").append(toIndentedString(metaTitle)).append("\n");
        sb.append("    packUnit: ").append(toIndentedString(packUnit)).append("\n");
        sb.append("    packUnitPlural: ").append(toIndentedString(packUnitPlural)).append("\n");
        sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
        sb.append("    availableStock: ").append(toIndentedString(availableStock)).append("\n");
        sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
        sb.append("    calculatedPrice: ").append(toIndentedString(calculatedPrice)).append("\n");
        sb.append("    calculatedPrices: ").append(toIndentedString(calculatedPrices)).append("\n");
        sb.append("    calculatedMaxPurchase: ").append(toIndentedString(calculatedMaxPurchase)).append("\n");
        sb.append("    calculatedCheapestPrice: ").append(toIndentedString(calculatedCheapestPrice)).append("\n");
        sb.append("    isNew: ").append(toIndentedString(isNew)).append("\n");
        sb.append("    sortedProperties: ").append(toIndentedString(sortedProperties)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("    translated: ").append(toIndentedString(translated)).append("\n");
        sb.append("    downloads: ").append(toIndentedString(downloads)).append("\n");
        sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
        sb.append("    children: ").append(toIndentedString(children)).append("\n");
        sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
        sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
        sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
        sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
        sb.append("    cover: ").append(toIndentedString(cover)).append("\n");
        sb.append("    cmsPage: ").append(toIndentedString(cmsPage)).append("\n");
        sb.append("    canonicalProduct: ").append(toIndentedString(canonicalProduct)).append("\n");
        sb.append("    media: ").append(toIndentedString(media)).append("\n");
        sb.append("    crossSellings: ").append(toIndentedString(crossSellings)).append("\n");
        sb.append("    configuratorSettings: ").append(toIndentedString(configuratorSettings)).append("\n");
        sb.append("    productReviews: ").append(toIndentedString(productReviews)).append("\n");
        sb.append("    mainCategories: ").append(toIndentedString(mainCategories)).append("\n");
        sb.append("    seoUrls: ").append(toIndentedString(seoUrls)).append("\n");
        sb.append("    options: ").append(toIndentedString(options)).append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
        sb.append("    streams: ").append(toIndentedString(streams)).append("\n");
        sb.append("    categoriesRo: ").append(toIndentedString(categoriesRo)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    seoCategory: ").append(toIndentedString(seoCategory)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

