/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;

/**
 * SendRecoveryMailRequest
 */
@JsonPropertyOrder({
  SendRecoveryMailRequest.JSON_PROPERTY_EMAIL,
  SendRecoveryMailRequest.JSON_PROPERTY_STOREFRONT_URL
})
@JsonTypeName("sendRecoveryMail_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class SendRecoveryMailRequest {
  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_STOREFRONT_URL = "storefrontUrl";
  private String storefrontUrl;

  public SendRecoveryMailRequest() {
  }

  public SendRecoveryMailRequest email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * E-Mail address to identify the customer
   * @return email
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(String email) {
    this.email = email;
  }


  public SendRecoveryMailRequest storefrontUrl(String storefrontUrl) {
    
    this.storefrontUrl = storefrontUrl;
    return this;
  }

   /**
   * URL of the storefront to use for the generated reset link. It has to be a domain that is configured in the sales channel domain settings.
   * @return storefrontUrl
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STOREFRONT_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStorefrontUrl() {
    return storefrontUrl;
  }


  @JsonProperty(JSON_PROPERTY_STOREFRONT_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStorefrontUrl(String storefrontUrl) {
    this.storefrontUrl = storefrontUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendRecoveryMailRequest sendRecoveryMailRequest = (SendRecoveryMailRequest) o;
    return Objects.equals(this.email, sendRecoveryMailRequest.email) &&
        Objects.equals(this.storefrontUrl, sendRecoveryMailRequest.storefrontUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, storefrontUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendRecoveryMailRequest {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    storefrontUrl: ").append(toIndentedString(storefrontUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

