/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Added since version: 6.0.0.0
 */
@JsonPropertyOrder({
  SeoUrl.JSON_PROPERTY_ID,
  SeoUrl.JSON_PROPERTY_SALES_CHANNEL_ID,
  SeoUrl.JSON_PROPERTY_LANGUAGE_ID,
  SeoUrl.JSON_PROPERTY_FOREIGN_KEY,
  SeoUrl.JSON_PROPERTY_ROUTE_NAME,
  SeoUrl.JSON_PROPERTY_PATH_INFO,
  SeoUrl.JSON_PROPERTY_SEO_PATH_INFO,
  SeoUrl.JSON_PROPERTY_IS_CANONICAL,
  SeoUrl.JSON_PROPERTY_IS_MODIFIED,
  SeoUrl.JSON_PROPERTY_IS_DELETED,
  SeoUrl.JSON_PROPERTY_URL,
  SeoUrl.JSON_PROPERTY_CUSTOM_FIELDS,
  SeoUrl.JSON_PROPERTY_IS_VALID,
  SeoUrl.JSON_PROPERTY_CREATED_AT,
  SeoUrl.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class SeoUrl {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_SALES_CHANNEL_ID = "salesChannelId";
  private String salesChannelId;

  public static final String JSON_PROPERTY_LANGUAGE_ID = "languageId";
  private String languageId;

  public static final String JSON_PROPERTY_FOREIGN_KEY = "foreignKey";
  private String foreignKey;

  public static final String JSON_PROPERTY_ROUTE_NAME = "routeName";
  private String routeName;

  public static final String JSON_PROPERTY_PATH_INFO = "pathInfo";
  private String pathInfo;

  public static final String JSON_PROPERTY_SEO_PATH_INFO = "seoPathInfo";
  private String seoPathInfo;

  public static final String JSON_PROPERTY_IS_CANONICAL = "isCanonical";
  private Boolean isCanonical;

  public static final String JSON_PROPERTY_IS_MODIFIED = "isModified";
  private Boolean isModified;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
  private Object customFields;

  public static final String JSON_PROPERTY_IS_VALID = "isValid";
  private Boolean isValid;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public SeoUrl() {
  }

  @JsonCreator
  public SeoUrl(
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
  ) {
    this();
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public SeoUrl id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public SeoUrl salesChannelId(String salesChannelId) {
    
    this.salesChannelId = salesChannelId;
    return this;
  }

   /**
   * Get salesChannelId
   * @return salesChannelId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SALES_CHANNEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSalesChannelId() {
    return salesChannelId;
  }


  @JsonProperty(JSON_PROPERTY_SALES_CHANNEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalesChannelId(String salesChannelId) {
    this.salesChannelId = salesChannelId;
  }


  public SeoUrl languageId(String languageId) {
    
    this.languageId = languageId;
    return this;
  }

   /**
   * Get languageId
   * @return languageId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LANGUAGE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguageId() {
    return languageId;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLanguageId(String languageId) {
    this.languageId = languageId;
  }


  public SeoUrl foreignKey(String foreignKey) {
    
    this.foreignKey = foreignKey;
    return this;
  }

   /**
   * Get foreignKey
   * @return foreignKey
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FOREIGN_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getForeignKey() {
    return foreignKey;
  }


  @JsonProperty(JSON_PROPERTY_FOREIGN_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setForeignKey(String foreignKey) {
    this.foreignKey = foreignKey;
  }


  public SeoUrl routeName(String routeName) {
    
    this.routeName = routeName;
    return this;
  }

   /**
   * Get routeName
   * @return routeName
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROUTE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRouteName() {
    return routeName;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteName(String routeName) {
    this.routeName = routeName;
  }


  public SeoUrl pathInfo(String pathInfo) {
    
    this.pathInfo = pathInfo;
    return this;
  }

   /**
   * Get pathInfo
   * @return pathInfo
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PATH_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPathInfo() {
    return pathInfo;
  }


  @JsonProperty(JSON_PROPERTY_PATH_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPathInfo(String pathInfo) {
    this.pathInfo = pathInfo;
  }


  public SeoUrl seoPathInfo(String seoPathInfo) {
    
    this.seoPathInfo = seoPathInfo;
    return this;
  }

   /**
   * Get seoPathInfo
   * @return seoPathInfo
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEO_PATH_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSeoPathInfo() {
    return seoPathInfo;
  }


  @JsonProperty(JSON_PROPERTY_SEO_PATH_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeoPathInfo(String seoPathInfo) {
    this.seoPathInfo = seoPathInfo;
  }


  public SeoUrl isCanonical(Boolean isCanonical) {
    
    this.isCanonical = isCanonical;
    return this;
  }

   /**
   * Get isCanonical
   * @return isCanonical
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_CANONICAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsCanonical() {
    return isCanonical;
  }


  @JsonProperty(JSON_PROPERTY_IS_CANONICAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsCanonical(Boolean isCanonical) {
    this.isCanonical = isCanonical;
  }


  public SeoUrl isModified(Boolean isModified) {
    
    this.isModified = isModified;
    return this;
  }

   /**
   * Get isModified
   * @return isModified
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsModified() {
    return isModified;
  }


  @JsonProperty(JSON_PROPERTY_IS_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsModified(Boolean isModified) {
    this.isModified = isModified;
  }


  public SeoUrl isDeleted(Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * Get isDeleted
   * @return isDeleted
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public SeoUrl url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Runtime field, cannot be used as part of the criteria.
   * @return url
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  public SeoUrl customFields(Object customFields) {
    
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomFields() {
    return customFields;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  public SeoUrl isValid(Boolean isValid) {
    
    this.isValid = isValid;
    return this;
  }

   /**
   * Runtime field, cannot be used as part of the criteria.
   * @return isValid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsValid() {
    return isValid;
  }


  @JsonProperty(JSON_PROPERTY_IS_VALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsValid(Boolean isValid) {
    this.isValid = isValid;
  }


   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeoUrl seoUrl = (SeoUrl) o;
    return Objects.equals(this.id, seoUrl.id) &&
        Objects.equals(this.salesChannelId, seoUrl.salesChannelId) &&
        Objects.equals(this.languageId, seoUrl.languageId) &&
        Objects.equals(this.foreignKey, seoUrl.foreignKey) &&
        Objects.equals(this.routeName, seoUrl.routeName) &&
        Objects.equals(this.pathInfo, seoUrl.pathInfo) &&
        Objects.equals(this.seoPathInfo, seoUrl.seoPathInfo) &&
        Objects.equals(this.isCanonical, seoUrl.isCanonical) &&
        Objects.equals(this.isModified, seoUrl.isModified) &&
        Objects.equals(this.isDeleted, seoUrl.isDeleted) &&
        Objects.equals(this.url, seoUrl.url) &&
        Objects.equals(this.customFields, seoUrl.customFields) &&
        Objects.equals(this.isValid, seoUrl.isValid) &&
        Objects.equals(this.createdAt, seoUrl.createdAt) &&
        Objects.equals(this.updatedAt, seoUrl.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, salesChannelId, languageId, foreignKey, routeName, pathInfo, seoPathInfo, isCanonical, isModified, isDeleted, url, customFields, isValid, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeoUrl {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    salesChannelId: ").append(toIndentedString(salesChannelId)).append("\n");
    sb.append("    languageId: ").append(toIndentedString(languageId)).append("\n");
    sb.append("    foreignKey: ").append(toIndentedString(foreignKey)).append("\n");
    sb.append("    routeName: ").append(toIndentedString(routeName)).append("\n");
    sb.append("    pathInfo: ").append(toIndentedString(pathInfo)).append("\n");
    sb.append("    seoPathInfo: ").append(toIndentedString(seoPathInfo)).append("\n");
    sb.append("    isCanonical: ").append(toIndentedString(isCanonical)).append("\n");
    sb.append("    isModified: ").append(toIndentedString(isModified)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    isValid: ").append(toIndentedString(isValid)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

