/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model.core;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Added since version: 6.0.0.0
 */
@JsonPropertyOrder({
  Category.JSON_PROPERTY_ID,
  Category.JSON_PROPERTY_VERSION_ID,
  Category.JSON_PROPERTY_PARENT_ID,
  Category.JSON_PROPERTY_PARENT_VERSION_ID,
  Category.JSON_PROPERTY_AFTER_CATEGORY_ID,
  Category.JSON_PROPERTY_AFTER_CATEGORY_VERSION_ID,
  Category.JSON_PROPERTY_MEDIA_ID,
  Category.JSON_PROPERTY_DISPLAY_NESTED_PRODUCTS,
  Category.JSON_PROPERTY_BREADCRUMB,
  Category.JSON_PROPERTY_LEVEL,
  Category.JSON_PROPERTY_PATH,
  Category.JSON_PROPERTY_CHILD_COUNT,
  Category.JSON_PROPERTY_TYPE,
  Category.JSON_PROPERTY_PRODUCT_ASSIGNMENT_TYPE,
  Category.JSON_PROPERTY_VISIBLE,
  Category.JSON_PROPERTY_ACTIVE,
  Category.JSON_PROPERTY_CMS_PAGE_ID_SWITCHED,
  Category.JSON_PROPERTY_VISIBLE_CHILD_COUNT,
  Category.JSON_PROPERTY_NAME,
  Category.JSON_PROPERTY_CUSTOM_FIELDS,
  Category.JSON_PROPERTY_LINK_TYPE,
  Category.JSON_PROPERTY_INTERNAL_LINK,
  Category.JSON_PROPERTY_EXTERNAL_LINK,
  Category.JSON_PROPERTY_LINK_NEW_TAB,
  Category.JSON_PROPERTY_DESCRIPTION,
  Category.JSON_PROPERTY_META_TITLE,
  Category.JSON_PROPERTY_META_DESCRIPTION,
  Category.JSON_PROPERTY_KEYWORDS,
  Category.JSON_PROPERTY_CMS_PAGE_ID,
  Category.JSON_PROPERTY_CMS_PAGE_VERSION_ID,
  Category.JSON_PROPERTY_CUSTOM_ENTITY_TYPE_ID,
  Category.JSON_PROPERTY_CREATED_AT,
  Category.JSON_PROPERTY_UPDATED_AT,
  Category.JSON_PROPERTY_TRANSLATED,
  Category.JSON_PROPERTY_PARENT,
  Category.JSON_PROPERTY_CHILDREN,
  Category.JSON_PROPERTY_MEDIA,
  Category.JSON_PROPERTY_TAGS,
  Category.JSON_PROPERTY_CMS_PAGE,
  Category.JSON_PROPERTY_SEO_URLS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class Category {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_VERSION_ID = "versionId";
  private String versionId;

  public static final String JSON_PROPERTY_PARENT_ID = "parentId";
  private String parentId;

  public static final String JSON_PROPERTY_PARENT_VERSION_ID = "parentVersionId";
  private String parentVersionId;

  public static final String JSON_PROPERTY_AFTER_CATEGORY_ID = "afterCategoryId";
  private String afterCategoryId;

  public static final String JSON_PROPERTY_AFTER_CATEGORY_VERSION_ID = "afterCategoryVersionId";
  private String afterCategoryVersionId;

  public static final String JSON_PROPERTY_MEDIA_ID = "mediaId";
  private String mediaId;

  public static final String JSON_PROPERTY_DISPLAY_NESTED_PRODUCTS = "displayNestedProducts";
  private Boolean displayNestedProducts;

  public static final String JSON_PROPERTY_BREADCRUMB = "breadcrumb";
  private List<Object> breadcrumb = new ArrayList<>();

  public static final String JSON_PROPERTY_LEVEL = "level";
  private Long level;

  public static final String JSON_PROPERTY_PATH = "path";
  private String path;

  public static final String JSON_PROPERTY_CHILD_COUNT = "childCount";
  private Long childCount;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_PRODUCT_ASSIGNMENT_TYPE = "productAssignmentType";
  private String productAssignmentType;

  public static final String JSON_PROPERTY_VISIBLE = "visible";
  private Boolean visible;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_CMS_PAGE_ID_SWITCHED = "cmsPageIdSwitched";
  private Boolean cmsPageIdSwitched;

  public static final String JSON_PROPERTY_VISIBLE_CHILD_COUNT = "visibleChildCount";
  private Long visibleChildCount;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
  private Object customFields;

  public static final String JSON_PROPERTY_LINK_TYPE = "linkType";
  private String linkType;

  public static final String JSON_PROPERTY_INTERNAL_LINK = "internalLink";
  private String internalLink;

  public static final String JSON_PROPERTY_EXTERNAL_LINK = "externalLink";
  private String externalLink;

  public static final String JSON_PROPERTY_LINK_NEW_TAB = "linkNewTab";
  private Boolean linkNewTab;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_META_TITLE = "metaTitle";
  private String metaTitle;

  public static final String JSON_PROPERTY_META_DESCRIPTION = "metaDescription";
  private String metaDescription;

  public static final String JSON_PROPERTY_KEYWORDS = "keywords";
  private String keywords;

  public static final String JSON_PROPERTY_CMS_PAGE_ID = "cmsPageId";
  private String cmsPageId;

  public static final String JSON_PROPERTY_CMS_PAGE_VERSION_ID = "cmsPageVersionId";
  private String cmsPageVersionId;

  public static final String JSON_PROPERTY_CUSTOM_ENTITY_TYPE_ID = "customEntityTypeId";
  private String customEntityTypeId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_TRANSLATED = "translated";
  private Object translated;

  public static final String JSON_PROPERTY_PARENT = "parent";
  private Category parent;

  public static final String JSON_PROPERTY_CHILDREN = "children";
  private List<Category> children = new ArrayList<>();

  public static final String JSON_PROPERTY_MEDIA = "media";
  private Media media;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<Tag> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_CMS_PAGE = "cmsPage";
  private CmsPage cmsPage;

  public static final String JSON_PROPERTY_SEO_URLS = "seoUrls";
  private List<SeoUrl> seoUrls = new ArrayList<>();

  public Category() {
  }

  @JsonCreator
  public Category(
    @JsonProperty(JSON_PROPERTY_BREADCRUMB) List<Object> breadcrumb, 
    @JsonProperty(JSON_PROPERTY_LEVEL) Long level, 
    @JsonProperty(JSON_PROPERTY_PATH) String path, 
    @JsonProperty(JSON_PROPERTY_CHILD_COUNT) Long childCount, 
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
  ) {
    this();
    this.breadcrumb = breadcrumb;
    this.level = level;
    this.path = path;
    this.childCount = childCount;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public Category id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public Category versionId(String versionId) {
    
    this.versionId = versionId;
    return this;
  }

   /**
   * Get versionId
   * @return versionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersionId() {
    return versionId;
  }


  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  public Category parentId(String parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentId() {
    return parentId;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  public Category parentVersionId(String parentVersionId) {
    
    this.parentVersionId = parentVersionId;
    return this;
  }

   /**
   * Get parentVersionId
   * @return parentVersionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentVersionId() {
    return parentVersionId;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentVersionId(String parentVersionId) {
    this.parentVersionId = parentVersionId;
  }


  public Category afterCategoryId(String afterCategoryId) {
    
    this.afterCategoryId = afterCategoryId;
    return this;
  }

   /**
   * Get afterCategoryId
   * @return afterCategoryId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AFTER_CATEGORY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAfterCategoryId() {
    return afterCategoryId;
  }


  @JsonProperty(JSON_PROPERTY_AFTER_CATEGORY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAfterCategoryId(String afterCategoryId) {
    this.afterCategoryId = afterCategoryId;
  }


  public Category afterCategoryVersionId(String afterCategoryVersionId) {
    
    this.afterCategoryVersionId = afterCategoryVersionId;
    return this;
  }

   /**
   * Get afterCategoryVersionId
   * @return afterCategoryVersionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AFTER_CATEGORY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAfterCategoryVersionId() {
    return afterCategoryVersionId;
  }


  @JsonProperty(JSON_PROPERTY_AFTER_CATEGORY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAfterCategoryVersionId(String afterCategoryVersionId) {
    this.afterCategoryVersionId = afterCategoryVersionId;
  }


  public Category mediaId(String mediaId) {
    
    this.mediaId = mediaId;
    return this;
  }

   /**
   * Get mediaId
   * @return mediaId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMediaId() {
    return mediaId;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }


  public Category displayNestedProducts(Boolean displayNestedProducts) {
    
    this.displayNestedProducts = displayNestedProducts;
    return this;
  }

   /**
   * Get displayNestedProducts
   * @return displayNestedProducts
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISPLAY_NESTED_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getDisplayNestedProducts() {
    return displayNestedProducts;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NESTED_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayNestedProducts(Boolean displayNestedProducts) {
    this.displayNestedProducts = displayNestedProducts;
  }


   /**
   * Get breadcrumb
   * @return breadcrumb
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BREADCRUMB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getBreadcrumb() {
    return breadcrumb;
  }




   /**
   * Get level
   * @return level
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLevel() {
    return level;
  }




   /**
   * Get path
   * @return path
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPath() {
    return path;
  }




   /**
   * Get childCount
   * @return childCount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHILD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getChildCount() {
    return childCount;
  }




  public Category type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }


  public Category productAssignmentType(String productAssignmentType) {
    
    this.productAssignmentType = productAssignmentType;
    return this;
  }

   /**
   * Get productAssignmentType
   * @return productAssignmentType
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRODUCT_ASSIGNMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductAssignmentType() {
    return productAssignmentType;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ASSIGNMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductAssignmentType(String productAssignmentType) {
    this.productAssignmentType = productAssignmentType;
  }


  public Category visible(Boolean visible) {
    
    this.visible = visible;
    return this;
  }

   /**
   * Get visible
   * @return visible
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVisible() {
    return visible;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisible(Boolean visible) {
    this.visible = visible;
  }


  public Category active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public Category cmsPageIdSwitched(Boolean cmsPageIdSwitched) {
    
    this.cmsPageIdSwitched = cmsPageIdSwitched;
    return this;
  }

   /**
   * Runtime field, cannot be used as part of the criteria.
   * @return cmsPageIdSwitched
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID_SWITCHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCmsPageIdSwitched() {
    return cmsPageIdSwitched;
  }


  @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID_SWITCHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmsPageIdSwitched(Boolean cmsPageIdSwitched) {
    this.cmsPageIdSwitched = cmsPageIdSwitched;
  }


  public Category visibleChildCount(Long visibleChildCount) {
    
    this.visibleChildCount = visibleChildCount;
    return this;
  }

   /**
   * Runtime field, cannot be used as part of the criteria.
   * @return visibleChildCount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISIBLE_CHILD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getVisibleChildCount() {
    return visibleChildCount;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_CHILD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleChildCount(Long visibleChildCount) {
    this.visibleChildCount = visibleChildCount;
  }


  public Category name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public Category customFields(Object customFields) {
    
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomFields() {
    return customFields;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  public Category linkType(String linkType) {
    
    this.linkType = linkType;
    return this;
  }

   /**
   * Get linkType
   * @return linkType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLinkType() {
    return linkType;
  }


  @JsonProperty(JSON_PROPERTY_LINK_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkType(String linkType) {
    this.linkType = linkType;
  }


  public Category internalLink(String internalLink) {
    
    this.internalLink = internalLink;
    return this;
  }

   /**
   * Get internalLink
   * @return internalLink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTERNAL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInternalLink() {
    return internalLink;
  }


  @JsonProperty(JSON_PROPERTY_INTERNAL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternalLink(String internalLink) {
    this.internalLink = internalLink;
  }


  public Category externalLink(String externalLink) {
    
    this.externalLink = externalLink;
    return this;
  }

   /**
   * Get externalLink
   * @return externalLink
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalLink() {
    return externalLink;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalLink(String externalLink) {
    this.externalLink = externalLink;
  }


  public Category linkNewTab(Boolean linkNewTab) {
    
    this.linkNewTab = linkNewTab;
    return this;
  }

   /**
   * Get linkNewTab
   * @return linkNewTab
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK_NEW_TAB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLinkNewTab() {
    return linkNewTab;
  }


  @JsonProperty(JSON_PROPERTY_LINK_NEW_TAB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkNewTab(Boolean linkNewTab) {
    this.linkNewTab = linkNewTab;
  }


  public Category description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Category metaTitle(String metaTitle) {
    
    this.metaTitle = metaTitle;
    return this;
  }

   /**
   * Get metaTitle
   * @return metaTitle
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetaTitle() {
    return metaTitle;
  }


  @JsonProperty(JSON_PROPERTY_META_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
  }


  public Category metaDescription(String metaDescription) {
    
    this.metaDescription = metaDescription;
    return this;
  }

   /**
   * Get metaDescription
   * @return metaDescription
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetaDescription() {
    return metaDescription;
  }


  @JsonProperty(JSON_PROPERTY_META_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
  }


  public Category keywords(String keywords) {
    
    this.keywords = keywords;
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeywords() {
    return keywords;
  }


  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }


  public Category cmsPageId(String cmsPageId) {
    
    this.cmsPageId = cmsPageId;
    return this;
  }

   /**
   * Get cmsPageId
   * @return cmsPageId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCmsPageId() {
    return cmsPageId;
  }


  @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmsPageId(String cmsPageId) {
    this.cmsPageId = cmsPageId;
  }


  public Category cmsPageVersionId(String cmsPageVersionId) {
    
    this.cmsPageVersionId = cmsPageVersionId;
    return this;
  }

   /**
   * Get cmsPageVersionId
   * @return cmsPageVersionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMS_PAGE_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCmsPageVersionId() {
    return cmsPageVersionId;
  }


  @JsonProperty(JSON_PROPERTY_CMS_PAGE_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmsPageVersionId(String cmsPageVersionId) {
    this.cmsPageVersionId = cmsPageVersionId;
  }


  public Category customEntityTypeId(String customEntityTypeId) {
    
    this.customEntityTypeId = customEntityTypeId;
    return this;
  }

   /**
   * Get customEntityTypeId
   * @return customEntityTypeId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_ENTITY_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomEntityTypeId() {
    return customEntityTypeId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_ENTITY_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomEntityTypeId(String customEntityTypeId) {
    this.customEntityTypeId = customEntityTypeId;
  }


   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  public Category translated(Object translated) {
    
    this.translated = translated;
    return this;
  }

   /**
   * Get translated
   * @return translated
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSLATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getTranslated() {
    return translated;
  }


  @JsonProperty(JSON_PROPERTY_TRANSLATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranslated(Object translated) {
    this.translated = translated;
  }


  public Category parent(Category parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Category getParent() {
    return parent;
  }


  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParent(Category parent) {
    this.parent = parent;
  }


  public Category children(List<Category> children) {
    
    this.children = children;
    return this;
  }

  public Category addChildrenItem(Category childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Category> getChildren() {
    return children;
  }


  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChildren(List<Category> children) {
    this.children = children;
  }


  public Category media(Media media) {
    
    this.media = media;
    return this;
  }

   /**
   * Get media
   * @return media
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Media getMedia() {
    return media;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedia(Media media) {
    this.media = media;
  }


  public Category tags(List<Tag> tags) {
    
    this.tags = tags;
    return this;
  }

  public Category addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Tag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  public Category cmsPage(CmsPage cmsPage) {
    
    this.cmsPage = cmsPage;
    return this;
  }

   /**
   * Get cmsPage
   * @return cmsPage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMS_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CmsPage getCmsPage() {
    return cmsPage;
  }


  @JsonProperty(JSON_PROPERTY_CMS_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmsPage(CmsPage cmsPage) {
    this.cmsPage = cmsPage;
  }


  public Category seoUrls(List<SeoUrl> seoUrls) {
    
    this.seoUrls = seoUrls;
    return this;
  }

  public Category addSeoUrlsItem(SeoUrl seoUrlsItem) {
    if (this.seoUrls == null) {
      this.seoUrls = new ArrayList<>();
    }
    this.seoUrls.add(seoUrlsItem);
    return this;
  }

   /**
   * Get seoUrls
   * @return seoUrls
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEO_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SeoUrl> getSeoUrls() {
    return seoUrls;
  }


  @JsonProperty(JSON_PROPERTY_SEO_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeoUrls(List<SeoUrl> seoUrls) {
    this.seoUrls = seoUrls;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Category category = (Category) o;
    return Objects.equals(this.id, category.id) &&
        Objects.equals(this.versionId, category.versionId) &&
        Objects.equals(this.parentId, category.parentId) &&
        Objects.equals(this.parentVersionId, category.parentVersionId) &&
        Objects.equals(this.afterCategoryId, category.afterCategoryId) &&
        Objects.equals(this.afterCategoryVersionId, category.afterCategoryVersionId) &&
        Objects.equals(this.mediaId, category.mediaId) &&
        Objects.equals(this.displayNestedProducts, category.displayNestedProducts) &&
        Objects.equals(this.breadcrumb, category.breadcrumb) &&
        Objects.equals(this.level, category.level) &&
        Objects.equals(this.path, category.path) &&
        Objects.equals(this.childCount, category.childCount) &&
        Objects.equals(this.type, category.type) &&
        Objects.equals(this.productAssignmentType, category.productAssignmentType) &&
        Objects.equals(this.visible, category.visible) &&
        Objects.equals(this.active, category.active) &&
        Objects.equals(this.cmsPageIdSwitched, category.cmsPageIdSwitched) &&
        Objects.equals(this.visibleChildCount, category.visibleChildCount) &&
        Objects.equals(this.name, category.name) &&
        Objects.equals(this.customFields, category.customFields) &&
        Objects.equals(this.linkType, category.linkType) &&
        Objects.equals(this.internalLink, category.internalLink) &&
        Objects.equals(this.externalLink, category.externalLink) &&
        Objects.equals(this.linkNewTab, category.linkNewTab) &&
        Objects.equals(this.description, category.description) &&
        Objects.equals(this.metaTitle, category.metaTitle) &&
        Objects.equals(this.metaDescription, category.metaDescription) &&
        Objects.equals(this.keywords, category.keywords) &&
        Objects.equals(this.cmsPageId, category.cmsPageId) &&
        Objects.equals(this.cmsPageVersionId, category.cmsPageVersionId) &&
        Objects.equals(this.customEntityTypeId, category.customEntityTypeId) &&
        Objects.equals(this.createdAt, category.createdAt) &&
        Objects.equals(this.updatedAt, category.updatedAt) &&
        Objects.equals(this.translated, category.translated) &&
        Objects.equals(this.parent, category.parent) &&
        Objects.equals(this.children, category.children) &&
        Objects.equals(this.media, category.media) &&
        Objects.equals(this.tags, category.tags) &&
        Objects.equals(this.cmsPage, category.cmsPage) &&
        Objects.equals(this.seoUrls, category.seoUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, versionId, parentId, parentVersionId, afterCategoryId, afterCategoryVersionId, mediaId, displayNestedProducts, breadcrumb, level, path, childCount, type, productAssignmentType, visible, active, cmsPageIdSwitched, visibleChildCount, name, customFields, linkType, internalLink, externalLink, linkNewTab, description, metaTitle, metaDescription, keywords, cmsPageId, cmsPageVersionId, customEntityTypeId, createdAt, updatedAt, translated, parent, children, media, tags, cmsPage, seoUrls);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Category {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    parentVersionId: ").append(toIndentedString(parentVersionId)).append("\n");
    sb.append("    afterCategoryId: ").append(toIndentedString(afterCategoryId)).append("\n");
    sb.append("    afterCategoryVersionId: ").append(toIndentedString(afterCategoryVersionId)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    displayNestedProducts: ").append(toIndentedString(displayNestedProducts)).append("\n");
    sb.append("    breadcrumb: ").append(toIndentedString(breadcrumb)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    childCount: ").append(toIndentedString(childCount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    productAssignmentType: ").append(toIndentedString(productAssignmentType)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    cmsPageIdSwitched: ").append(toIndentedString(cmsPageIdSwitched)).append("\n");
    sb.append("    visibleChildCount: ").append(toIndentedString(visibleChildCount)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
    sb.append("    internalLink: ").append(toIndentedString(internalLink)).append("\n");
    sb.append("    externalLink: ").append(toIndentedString(externalLink)).append("\n");
    sb.append("    linkNewTab: ").append(toIndentedString(linkNewTab)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    metaTitle: ").append(toIndentedString(metaTitle)).append("\n");
    sb.append("    metaDescription: ").append(toIndentedString(metaDescription)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    cmsPageId: ").append(toIndentedString(cmsPageId)).append("\n");
    sb.append("    cmsPageVersionId: ").append(toIndentedString(cmsPageVersionId)).append("\n");
    sb.append("    customEntityTypeId: ").append(toIndentedString(customEntityTypeId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    translated: ").append(toIndentedString(translated)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    cmsPage: ").append(toIndentedString(cmsPage)).append("\n");
    sb.append("    seoUrls: ").append(toIndentedString(seoUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

