/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model.core;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CategoryJsonApiAllOfRelationshipsTags
 */
@JsonPropertyOrder({
  CategoryJsonApiAllOfRelationshipsTags.JSON_PROPERTY_LINKS,
  CategoryJsonApiAllOfRelationshipsTags.JSON_PROPERTY_DATA
})
@JsonTypeName("CategoryJsonApi_allOf_relationships_tags")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class CategoryJsonApiAllOfRelationshipsTags {
  public static final String JSON_PROPERTY_LINKS = "links";
  private CategoryJsonApiAllOfRelationshipsTagsLinks links;

  public static final String JSON_PROPERTY_DATA = "data";
  private List<CategoryJsonApiAllOfRelationshipsTagsData> data = new ArrayList<>();

  public CategoryJsonApiAllOfRelationshipsTags() {
  }

  public CategoryJsonApiAllOfRelationshipsTags links(CategoryJsonApiAllOfRelationshipsTagsLinks links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CategoryJsonApiAllOfRelationshipsTagsLinks getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(CategoryJsonApiAllOfRelationshipsTagsLinks links) {
    this.links = links;
  }


  public CategoryJsonApiAllOfRelationshipsTags data(List<CategoryJsonApiAllOfRelationshipsTagsData> data) {
    
    this.data = data;
    return this;
  }

  public CategoryJsonApiAllOfRelationshipsTags addDataItem(CategoryJsonApiAllOfRelationshipsTagsData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CategoryJsonApiAllOfRelationshipsTagsData> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(List<CategoryJsonApiAllOfRelationshipsTagsData> data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryJsonApiAllOfRelationshipsTags categoryJsonApiAllOfRelationshipsTags = (CategoryJsonApiAllOfRelationshipsTags) o;
    return Objects.equals(this.links, categoryJsonApiAllOfRelationshipsTags.links) &&
        Objects.equals(this.data, categoryJsonApiAllOfRelationshipsTags.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryJsonApiAllOfRelationshipsTags {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
