/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model.core;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Added since version: 6.4.0.0
 */
@JsonPropertyOrder({
  LandingPage.JSON_PROPERTY_ID,
  LandingPage.JSON_PROPERTY_VERSION_ID,
  LandingPage.JSON_PROPERTY_ACTIVE,
  LandingPage.JSON_PROPERTY_NAME,
  LandingPage.JSON_PROPERTY_CUSTOM_FIELDS,
  LandingPage.JSON_PROPERTY_SLOT_CONFIG,
  LandingPage.JSON_PROPERTY_META_TITLE,
  LandingPage.JSON_PROPERTY_META_DESCRIPTION,
  LandingPage.JSON_PROPERTY_KEYWORDS,
  LandingPage.JSON_PROPERTY_URL,
  LandingPage.JSON_PROPERTY_CMS_PAGE_ID,
  LandingPage.JSON_PROPERTY_CMS_PAGE_VERSION_ID,
  LandingPage.JSON_PROPERTY_CREATED_AT,
  LandingPage.JSON_PROPERTY_UPDATED_AT,
  LandingPage.JSON_PROPERTY_TRANSLATED,
  LandingPage.JSON_PROPERTY_CMS_PAGE,
  LandingPage.JSON_PROPERTY_SEO_URLS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class LandingPage {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_VERSION_ID = "versionId";
  private String versionId;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
  private Object customFields;

  public static final String JSON_PROPERTY_SLOT_CONFIG = "slotConfig";
  private Object slotConfig;

  public static final String JSON_PROPERTY_META_TITLE = "metaTitle";
  private String metaTitle;

  public static final String JSON_PROPERTY_META_DESCRIPTION = "metaDescription";
  private String metaDescription;

  public static final String JSON_PROPERTY_KEYWORDS = "keywords";
  private String keywords;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_CMS_PAGE_ID = "cmsPageId";
  private String cmsPageId;

  public static final String JSON_PROPERTY_CMS_PAGE_VERSION_ID = "cmsPageVersionId";
  private String cmsPageVersionId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_TRANSLATED = "translated";
  private Object translated;

  public static final String JSON_PROPERTY_CMS_PAGE = "cmsPage";
  private CmsPage cmsPage;

  public static final String JSON_PROPERTY_SEO_URLS = "seoUrls";
  private List<SeoUrl> seoUrls = new ArrayList<>();

  public LandingPage() {
  }

  @JsonCreator
  public LandingPage(
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
  ) {
    this();
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public LandingPage id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public LandingPage versionId(String versionId) {
    
    this.versionId = versionId;
    return this;
  }

   /**
   * Get versionId
   * @return versionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersionId() {
    return versionId;
  }


  @JsonProperty(JSON_PROPERTY_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  public LandingPage active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public LandingPage name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public LandingPage customFields(Object customFields) {
    
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomFields() {
    return customFields;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  public LandingPage slotConfig(Object slotConfig) {
    
    this.slotConfig = slotConfig;
    return this;
  }

   /**
   * Get slotConfig
   * @return slotConfig
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLOT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getSlotConfig() {
    return slotConfig;
  }


  @JsonProperty(JSON_PROPERTY_SLOT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSlotConfig(Object slotConfig) {
    this.slotConfig = slotConfig;
  }


  public LandingPage metaTitle(String metaTitle) {
    
    this.metaTitle = metaTitle;
    return this;
  }

   /**
   * Get metaTitle
   * @return metaTitle
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetaTitle() {
    return metaTitle;
  }


  @JsonProperty(JSON_PROPERTY_META_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
  }


  public LandingPage metaDescription(String metaDescription) {
    
    this.metaDescription = metaDescription;
    return this;
  }

   /**
   * Get metaDescription
   * @return metaDescription
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMetaDescription() {
    return metaDescription;
  }


  @JsonProperty(JSON_PROPERTY_META_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
  }


  public LandingPage keywords(String keywords) {
    
    this.keywords = keywords;
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeywords() {
    return keywords;
  }


  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }


  public LandingPage url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(String url) {
    this.url = url;
  }


  public LandingPage cmsPageId(String cmsPageId) {
    
    this.cmsPageId = cmsPageId;
    return this;
  }

   /**
   * Get cmsPageId
   * @return cmsPageId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCmsPageId() {
    return cmsPageId;
  }


  @JsonProperty(JSON_PROPERTY_CMS_PAGE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmsPageId(String cmsPageId) {
    this.cmsPageId = cmsPageId;
  }


  public LandingPage cmsPageVersionId(String cmsPageVersionId) {
    
    this.cmsPageVersionId = cmsPageVersionId;
    return this;
  }

   /**
   * Get cmsPageVersionId
   * @return cmsPageVersionId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMS_PAGE_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCmsPageVersionId() {
    return cmsPageVersionId;
  }


  @JsonProperty(JSON_PROPERTY_CMS_PAGE_VERSION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmsPageVersionId(String cmsPageVersionId) {
    this.cmsPageVersionId = cmsPageVersionId;
  }


   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  public LandingPage translated(Object translated) {
    
    this.translated = translated;
    return this;
  }

   /**
   * Get translated
   * @return translated
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSLATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getTranslated() {
    return translated;
  }


  @JsonProperty(JSON_PROPERTY_TRANSLATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranslated(Object translated) {
    this.translated = translated;
  }


  public LandingPage cmsPage(CmsPage cmsPage) {
    
    this.cmsPage = cmsPage;
    return this;
  }

   /**
   * Get cmsPage
   * @return cmsPage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CMS_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CmsPage getCmsPage() {
    return cmsPage;
  }


  @JsonProperty(JSON_PROPERTY_CMS_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCmsPage(CmsPage cmsPage) {
    this.cmsPage = cmsPage;
  }


  public LandingPage seoUrls(List<SeoUrl> seoUrls) {
    
    this.seoUrls = seoUrls;
    return this;
  }

  public LandingPage addSeoUrlsItem(SeoUrl seoUrlsItem) {
    if (this.seoUrls == null) {
      this.seoUrls = new ArrayList<>();
    }
    this.seoUrls.add(seoUrlsItem);
    return this;
  }

   /**
   * Get seoUrls
   * @return seoUrls
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEO_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SeoUrl> getSeoUrls() {
    return seoUrls;
  }


  @JsonProperty(JSON_PROPERTY_SEO_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeoUrls(List<SeoUrl> seoUrls) {
    this.seoUrls = seoUrls;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandingPage landingPage = (LandingPage) o;
    return Objects.equals(this.id, landingPage.id) &&
        Objects.equals(this.versionId, landingPage.versionId) &&
        Objects.equals(this.active, landingPage.active) &&
        Objects.equals(this.name, landingPage.name) &&
        Objects.equals(this.customFields, landingPage.customFields) &&
        Objects.equals(this.slotConfig, landingPage.slotConfig) &&
        Objects.equals(this.metaTitle, landingPage.metaTitle) &&
        Objects.equals(this.metaDescription, landingPage.metaDescription) &&
        Objects.equals(this.keywords, landingPage.keywords) &&
        Objects.equals(this.url, landingPage.url) &&
        Objects.equals(this.cmsPageId, landingPage.cmsPageId) &&
        Objects.equals(this.cmsPageVersionId, landingPage.cmsPageVersionId) &&
        Objects.equals(this.createdAt, landingPage.createdAt) &&
        Objects.equals(this.updatedAt, landingPage.updatedAt) &&
        Objects.equals(this.translated, landingPage.translated) &&
        Objects.equals(this.cmsPage, landingPage.cmsPage) &&
        Objects.equals(this.seoUrls, landingPage.seoUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, versionId, active, name, customFields, slotConfig, metaTitle, metaDescription, keywords, url, cmsPageId, cmsPageVersionId, createdAt, updatedAt, translated, cmsPage, seoUrls);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandingPage {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    slotConfig: ").append(toIndentedString(slotConfig)).append("\n");
    sb.append("    metaTitle: ").append(toIndentedString(metaTitle)).append("\n");
    sb.append("    metaDescription: ").append(toIndentedString(metaDescription)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    cmsPageId: ").append(toIndentedString(cmsPageId)).append("\n");
    sb.append("    cmsPageVersionId: ").append(toIndentedString(cmsPageVersionId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    translated: ").append(toIndentedString(translated)).append("\n");
    sb.append("    cmsPage: ").append(toIndentedString(cmsPage)).append("\n");
    sb.append("    seoUrls: ").append(toIndentedString(seoUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

