/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model.core;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;

/**
 * LanguageJsonApiAllOfRelationships
 */
@JsonPropertyOrder({
  LanguageJsonApiAllOfRelationships.JSON_PROPERTY_PARENT,
  LanguageJsonApiAllOfRelationships.JSON_PROPERTY_LOCALE,
  LanguageJsonApiAllOfRelationships.JSON_PROPERTY_TRANSLATION_CODE,
  LanguageJsonApiAllOfRelationships.JSON_PROPERTY_CHILDREN
})
@JsonTypeName("LanguageJsonApi_allOf_relationships")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class LanguageJsonApiAllOfRelationships {
  public static final String JSON_PROPERTY_PARENT = "parent";
  private LanguageJsonApiAllOfRelationshipsParent parent;

  public static final String JSON_PROPERTY_LOCALE = "locale";
  private LanguageJsonApiAllOfRelationshipsLocale locale;

  public static final String JSON_PROPERTY_TRANSLATION_CODE = "translationCode";
  private LanguageJsonApiAllOfRelationshipsTranslationCode translationCode;

  public static final String JSON_PROPERTY_CHILDREN = "children";
  private LanguageJsonApiAllOfRelationshipsChildren children;

  public LanguageJsonApiAllOfRelationships() {
  }

  public LanguageJsonApiAllOfRelationships parent(LanguageJsonApiAllOfRelationshipsParent parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LanguageJsonApiAllOfRelationshipsParent getParent() {
    return parent;
  }


  @JsonProperty(JSON_PROPERTY_PARENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParent(LanguageJsonApiAllOfRelationshipsParent parent) {
    this.parent = parent;
  }


  public LanguageJsonApiAllOfRelationships locale(LanguageJsonApiAllOfRelationshipsLocale locale) {
    
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LanguageJsonApiAllOfRelationshipsLocale getLocale() {
    return locale;
  }


  @JsonProperty(JSON_PROPERTY_LOCALE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocale(LanguageJsonApiAllOfRelationshipsLocale locale) {
    this.locale = locale;
  }


  public LanguageJsonApiAllOfRelationships translationCode(LanguageJsonApiAllOfRelationshipsTranslationCode translationCode) {
    
    this.translationCode = translationCode;
    return this;
  }

   /**
   * Get translationCode
   * @return translationCode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSLATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LanguageJsonApiAllOfRelationshipsTranslationCode getTranslationCode() {
    return translationCode;
  }


  @JsonProperty(JSON_PROPERTY_TRANSLATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranslationCode(LanguageJsonApiAllOfRelationshipsTranslationCode translationCode) {
    this.translationCode = translationCode;
  }


  public LanguageJsonApiAllOfRelationships children(LanguageJsonApiAllOfRelationshipsChildren children) {
    
    this.children = children;
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LanguageJsonApiAllOfRelationshipsChildren getChildren() {
    return children;
  }


  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChildren(LanguageJsonApiAllOfRelationshipsChildren children) {
    this.children = children;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LanguageJsonApiAllOfRelationships languageJsonApiAllOfRelationships = (LanguageJsonApiAllOfRelationships) o;
    return Objects.equals(this.parent, languageJsonApiAllOfRelationships.parent) &&
        Objects.equals(this.locale, languageJsonApiAllOfRelationships.locale) &&
        Objects.equals(this.translationCode, languageJsonApiAllOfRelationships.translationCode) &&
        Objects.equals(this.children, languageJsonApiAllOfRelationships.children);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parent, locale, translationCode, children);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LanguageJsonApiAllOfRelationships {\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    translationCode: ").append(toIndentedString(translationCode)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

