/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model.core;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;

/**
 * Customer group of the current user
 */
@JsonPropertyOrder({
  SalesChannelContextAllOfCurrentCustomerGroup.JSON_PROPERTY_NAME,
  SalesChannelContextAllOfCurrentCustomerGroup.JSON_PROPERTY_DISPLAY_GROSS
})
@JsonTypeName("SalesChannelContext_allOf_currentCustomerGroup")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class SalesChannelContextAllOfCurrentCustomerGroup {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DISPLAY_GROSS = "displayGross";
  private Boolean displayGross;

  public SalesChannelContextAllOfCurrentCustomerGroup() {
  }

  public SalesChannelContextAllOfCurrentCustomerGroup name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public SalesChannelContextAllOfCurrentCustomerGroup displayGross(Boolean displayGross) {
    
    this.displayGross = displayGross;
    return this;
  }

   /**
   * Get displayGross
   * @return displayGross
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_GROSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisplayGross() {
    return displayGross;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_GROSS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayGross(Boolean displayGross) {
    this.displayGross = displayGross;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesChannelContextAllOfCurrentCustomerGroup salesChannelContextAllOfCurrentCustomerGroup = (SalesChannelContextAllOfCurrentCustomerGroup) o;
    return Objects.equals(this.name, salesChannelContextAllOfCurrentCustomerGroup.name) &&
        Objects.equals(this.displayGross, salesChannelContextAllOfCurrentCustomerGroup.displayGross);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, displayGross);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesChannelContextAllOfCurrentCustomerGroup {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    displayGross: ").append(toIndentedString(displayGross)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

