/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model.core;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Added since version: 6.0.0.0
 */
@JsonPropertyOrder({
  ShippingMethod.JSON_PROPERTY_ID,
  ShippingMethod.JSON_PROPERTY_NAME,
  ShippingMethod.JSON_PROPERTY_ACTIVE,
  ShippingMethod.JSON_PROPERTY_POSITION,
  ShippingMethod.JSON_PROPERTY_CUSTOM_FIELDS,
  ShippingMethod.JSON_PROPERTY_MEDIA_ID,
  ShippingMethod.JSON_PROPERTY_DELIVERY_TIME_ID,
  ShippingMethod.JSON_PROPERTY_TAX_TYPE,
  ShippingMethod.JSON_PROPERTY_DESCRIPTION,
  ShippingMethod.JSON_PROPERTY_TRACKING_URL,
  ShippingMethod.JSON_PROPERTY_TECHNICAL_NAME,
  ShippingMethod.JSON_PROPERTY_CREATED_AT,
  ShippingMethod.JSON_PROPERTY_UPDATED_AT,
  ShippingMethod.JSON_PROPERTY_TRANSLATED,
  ShippingMethod.JSON_PROPERTY_DELIVERY_TIME,
  ShippingMethod.JSON_PROPERTY_AVAILABILITY_RULE,
  ShippingMethod.JSON_PROPERTY_PRICES,
  ShippingMethod.JSON_PROPERTY_MEDIA,
  ShippingMethod.JSON_PROPERTY_TAGS,
  ShippingMethod.JSON_PROPERTY_TAX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class ShippingMethod {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_POSITION = "position";
  private Long position;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
  private Object customFields;

  public static final String JSON_PROPERTY_MEDIA_ID = "mediaId";
  private String mediaId;

  public static final String JSON_PROPERTY_DELIVERY_TIME_ID = "deliveryTimeId";
  private String deliveryTimeId;

  public static final String JSON_PROPERTY_TAX_TYPE = "taxType";
  private String taxType;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_TRACKING_URL = "trackingUrl";
  private String trackingUrl;

  public static final String JSON_PROPERTY_TECHNICAL_NAME = "technicalName";
  private String technicalName;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_TRANSLATED = "translated";
  private JsonNode translated;

  public static final String JSON_PROPERTY_DELIVERY_TIME = "deliveryTime";
  private DeliveryTime deliveryTime;

  public static final String JSON_PROPERTY_AVAILABILITY_RULE = "availabilityRule";
  private Rule availabilityRule;

  public static final String JSON_PROPERTY_PRICES = "prices";
  private List<ShippingMethodPrice> prices = new ArrayList<>();

  public static final String JSON_PROPERTY_MEDIA = "media";
  private Media media;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<Tag> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_TAX = "tax";
  private Tax tax;

  public ShippingMethod() {
  }

  @JsonCreator
  public ShippingMethod(
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
  ) {
    this();
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  public ShippingMethod id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ShippingMethod name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public ShippingMethod active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public ShippingMethod position(Long position) {
    
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPosition() {
    return position;
  }


  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosition(Long position) {
    this.position = position;
  }


  public ShippingMethod customFields(Object customFields) {
    
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomFields() {
    return customFields;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


  public ShippingMethod mediaId(String mediaId) {
    
    this.mediaId = mediaId;
    return this;
  }

   /**
   * Get mediaId
   * @return mediaId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMediaId() {
    return mediaId;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMediaId(String mediaId) {
    this.mediaId = mediaId;
  }


  public ShippingMethod deliveryTimeId(String deliveryTimeId) {
    
    this.deliveryTimeId = deliveryTimeId;
    return this;
  }

   /**
   * Get deliveryTimeId
   * @return deliveryTimeId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELIVERY_TIME_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeliveryTimeId() {
    return deliveryTimeId;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TIME_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeliveryTimeId(String deliveryTimeId) {
    this.deliveryTimeId = deliveryTimeId;
  }


  public ShippingMethod taxType(String taxType) {
    
    this.taxType = taxType;
    return this;
  }

   /**
   * Get taxType
   * @return taxType
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TAX_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTaxType() {
    return taxType;
  }


  @JsonProperty(JSON_PROPERTY_TAX_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTaxType(String taxType) {
    this.taxType = taxType;
  }


  public ShippingMethod description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ShippingMethod trackingUrl(String trackingUrl) {
    
    this.trackingUrl = trackingUrl;
    return this;
  }

   /**
   * Get trackingUrl
   * @return trackingUrl
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackingUrl() {
    return trackingUrl;
  }


  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingUrl(String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }


  public ShippingMethod technicalName(String technicalName) {
    
    this.technicalName = technicalName;
    return this;
  }

   /**
   * Get technicalName
   * @return technicalName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TECHNICAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTechnicalName() {
    return technicalName;
  }


  @JsonProperty(JSON_PROPERTY_TECHNICAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTechnicalName(String technicalName) {
    this.technicalName = technicalName;
  }


   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  public ShippingMethod translated(JsonNode translated) {
    
    this.translated = translated;
    return this;
  }

   /**
   * Get translated
   * @return translated
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSLATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNode getTranslated() {
    return translated;
  }


  @JsonProperty(JSON_PROPERTY_TRANSLATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTranslated(JsonNode translated) {
    this.translated = translated;
  }


  public ShippingMethod deliveryTime(DeliveryTime deliveryTime) {
    
    this.deliveryTime = deliveryTime;
    return this;
  }

   /**
   * Get deliveryTime
   * @return deliveryTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryTime getDeliveryTime() {
    return deliveryTime;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryTime(DeliveryTime deliveryTime) {
    this.deliveryTime = deliveryTime;
  }


  public ShippingMethod availabilityRule(Rule availabilityRule) {
    
    this.availabilityRule = availabilityRule;
    return this;
  }

   /**
   * Get availabilityRule
   * @return availabilityRule
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVAILABILITY_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Rule getAvailabilityRule() {
    return availabilityRule;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABILITY_RULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailabilityRule(Rule availabilityRule) {
    this.availabilityRule = availabilityRule;
  }


  public ShippingMethod prices(List<ShippingMethodPrice> prices) {
    
    this.prices = prices;
    return this;
  }

  public ShippingMethod addPricesItem(ShippingMethodPrice pricesItem) {
    if (this.prices == null) {
      this.prices = new ArrayList<>();
    }
    this.prices.add(pricesItem);
    return this;
  }

   /**
   * Get prices
   * @return prices
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ShippingMethodPrice> getPrices() {
    return prices;
  }


  @JsonProperty(JSON_PROPERTY_PRICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrices(List<ShippingMethodPrice> prices) {
    this.prices = prices;
  }


  public ShippingMethod media(Media media) {
    
    this.media = media;
    return this;
  }

   /**
   * Get media
   * @return media
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Media getMedia() {
    return media;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedia(Media media) {
    this.media = media;
  }


  public ShippingMethod tags(List<Tag> tags) {
    
    this.tags = tags;
    return this;
  }

  public ShippingMethod addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Tag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  public ShippingMethod tax(Tax tax) {
    
    this.tax = tax;
    return this;
  }

   /**
   * Get tax
   * @return tax
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Tax getTax() {
    return tax;
  }


  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTax(Tax tax) {
    this.tax = tax;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingMethod shippingMethod = (ShippingMethod) o;
    return Objects.equals(this.id, shippingMethod.id) &&
        Objects.equals(this.name, shippingMethod.name) &&
        Objects.equals(this.active, shippingMethod.active) &&
        Objects.equals(this.position, shippingMethod.position) &&
        Objects.equals(this.customFields, shippingMethod.customFields) &&
        Objects.equals(this.mediaId, shippingMethod.mediaId) &&
        Objects.equals(this.deliveryTimeId, shippingMethod.deliveryTimeId) &&
        Objects.equals(this.taxType, shippingMethod.taxType) &&
        Objects.equals(this.description, shippingMethod.description) &&
        Objects.equals(this.trackingUrl, shippingMethod.trackingUrl) &&
        Objects.equals(this.technicalName, shippingMethod.technicalName) &&
        Objects.equals(this.createdAt, shippingMethod.createdAt) &&
        Objects.equals(this.updatedAt, shippingMethod.updatedAt) &&
        Objects.equals(this.translated, shippingMethod.translated) &&
        Objects.equals(this.deliveryTime, shippingMethod.deliveryTime) &&
        Objects.equals(this.availabilityRule, shippingMethod.availabilityRule) &&
        Objects.equals(this.prices, shippingMethod.prices) &&
        Objects.equals(this.media, shippingMethod.media) &&
        Objects.equals(this.tags, shippingMethod.tags) &&
        Objects.equals(this.tax, shippingMethod.tax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, active, position, customFields, mediaId, deliveryTimeId, taxType, description, trackingUrl, technicalName, createdAt, updatedAt, translated, deliveryTime, availabilityRule, prices, media, tags, tax);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingMethod {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    deliveryTimeId: ").append(toIndentedString(deliveryTimeId)).append("\n");
    sb.append("    taxType: ").append(toIndentedString(taxType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("    technicalName: ").append(toIndentedString(technicalName)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    translated: ").append(toIndentedString(translated)).append("\n");
    sb.append("    deliveryTime: ").append(toIndentedString(deliveryTime)).append("\n");
    sb.append("    availabilityRule: ").append(toIndentedString(availabilityRule)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

