/*
 * Shopware Store API
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Store API
 *
 * The version of the OpenAPI document: 6.5.7.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codebarista.shopware.model.core;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Added since version: 6.0.0.0
 */
@JsonPropertyOrder({
        Snippet.JSON_PROPERTY_ID,
        Snippet.JSON_PROPERTY_SET_ID,
        Snippet.JSON_PROPERTY_TRANSLATION_KEY,
        Snippet.JSON_PROPERTY_VALUE,
        Snippet.JSON_PROPERTY_CUSTOM_FIELDS,
        Snippet.JSON_PROPERTY_CREATED_AT,
        Snippet.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-06-10T11:26:02.541008353+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class Snippet {
    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_SET_ID = "setId";
    private String setId;

    public static final String JSON_PROPERTY_TRANSLATION_KEY = "translationKey";
    private String translationKey;

    public static final String JSON_PROPERTY_VALUE = "value";
    private String value;

    public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
    private Object customFields;

    public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
    private OffsetDateTime createdAt;

    public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
    private OffsetDateTime updatedAt;

    public Snippet() {
    }

    @JsonCreator
    public Snippet(
            @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt,
            @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
    ) {
        this();
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Snippet id(String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }


    /**
     * Get setId
     *
     * @return setId
     **/
    @JsonProperty(JSON_PROPERTY_SET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getSetId() {
        return setId;
    }


    @JsonProperty(JSON_PROPERTY_SET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSetId(String setId) {
        this.setId = setId;
    }


    public Snippet translationKey(String translationKey) {

        this.translationKey = translationKey;
        return this;
    }

    /**
     * Get translationKey
     *
     * @return translationKey
     **/
    @JsonProperty(JSON_PROPERTY_TRANSLATION_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getTranslationKey() {
        return translationKey;
    }


    @JsonProperty(JSON_PROPERTY_TRANSLATION_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTranslationKey(String translationKey) {
        this.translationKey = translationKey;
    }


    public Snippet value(String value) {

        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     **/
    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getValue() {
        return value;
    }


    @JsonProperty(JSON_PROPERTY_VALUE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setValue(String value) {
        this.value = value;
    }


    public Snippet customFields(Object customFields) {

        this.customFields = customFields;
        return this;
    }

    /**
     * Get customFields
     *
     * @return customFields
     **/
    @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Object getCustomFields() {
        return customFields;
    }


    @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCustomFields(Object customFields) {
        this.customFields = customFields;
    }


    /**
     * Get createdAt
     *
     * @return createdAt
     **/
    @JsonProperty(JSON_PROPERTY_CREATED_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }


    /**
     * Get updatedAt
     *
     * @return updatedAt
     **/
    @JsonProperty(JSON_PROPERTY_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Snippet snippet = (Snippet) o;
        return Objects.equals(this.id, snippet.id) &&
                Objects.equals(this.setId, snippet.setId) &&
                Objects.equals(this.translationKey, snippet.translationKey) &&
                Objects.equals(this.value, snippet.value) &&
                Objects.equals(this.customFields, snippet.customFields) &&
                Objects.equals(this.createdAt, snippet.createdAt) &&
                Objects.equals(this.updatedAt, snippet.updatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, setId, translationKey, value, customFields, createdAt, updatedAt);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Snippet {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    setId: ").append(toIndentedString(setId)).append("\n");
        sb.append("    translationKey: ").append(toIndentedString(translationKey)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
